### ISSUE TITLE
String height calculations are not respected by ActiveLabel

### ISSUE THREAD

**Issue by kaandedeoglu** [optonaut/ActiveLabel.swift#10]
Hey, I'm setting up my label in a UICollectionViewCell subclass where I calculate the label height beforehand, but I'm seeing clipping when I switch from `UILabel` to `ActiveLabel`. Here's my code snippet. (I also see the same results when I use sizeThatFits to calculate the height)

```swift
let attributedComment = NSMutableAttributedString(string: comment, attributes: [NSFontAttributeName : PostContentView.commentFont, NSParagraphStyleAttributeName : Utility.paragraphStyle])
let height = attributedComment.heightWithConstrainedWidth(frame.size.width)
let commentLabel = ActiveLabel(frame: CGRect(x: 0, y: 0, width: CGRectGetWidth(frame), height: height))
commentLabel.numberOfLines = 0
commentLabel.attributedText = attributedComment
addSubview(commentLabel)


//NSAttributedString Extension
extension NSAttributedString {
    func heightWithConstrainedWidth(width: CGFloat) -> CGFloat {
        let constraintRect = CGSize(width: width, height: CGFloat.max)
        let boundingBox = self.boundingRectWithSize(constraintRect, options: NSStringDrawingOptions.UsesLineFragmentOrigin, context: nil)
        
        return ceil(boundingBox.height)
    }
}
```

Below are two images using `ActiveLabel` and `UILabel`, respectively.

![screen shot 2015-10-07 at 3 57 52 pm](https://cloud.githubusercontent.com/assets/1566836/10338146/015c029e-6d0d-11e5-8e7b-89a5a2550e7d.png)

![screen shot 2015-10-07 at 4 01 43 pm](https://cloud.githubusercontent.com/assets/1566836/10338148/053db952-6d0d-11e5-8677-86147e8376ed.png)

Is there a gotcha that I'm missing here? (the paragraph style just provides a `lineSpacing` value of 6 btw)

**Comment by schickling** [comment]
Hi @kaandedeoglu. Thank you for opening this issue. Unfortunately we don't have the capacity to put further investigation into this at the moment. However we would be more than happy to merge a pull request if needed.

**Comment by kaandedeoglu** [comment]
@schickling Thank you for the reply, I'll try to find a solution and send a pull request - :)

**Comment by schickling** [comment]
Great. You can keep the issue open in the meanwhile :+1:

**Comment by kaandedeoglu** [comment]
@schickling Can you please update the podspec for 0.2.3 as well?

**Comment by schickling** [comment]
Oh I'm sorry, I'm a Carthage user and always forget about that :P

**Comment by kyxer** [comment]
Could you fix this? I have the same problem. @kaandedeoglu Thanks for help

**Comment by kaandedeoglu** [comment]
@kyxer this has been fixed for a while now actually.
