### ISSUE TITLE
handleMentionTap and else won't works

### ISSUE THREAD

**Issue by black-lotus** [optonaut/ActiveLabel.swift#101]
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/3261560/17394402/10e9163c-5a53-11e6-903f-61396602c52d.gif)

Is anyone experience with my issue :(

Thanks

**Comment by black-lotus** [comment]
It's working when i tap for long time, but still not working for single tap

**Comment by black-lotus** [comment]
I solve it, my bad
there is UITapGestureRecognizer in my code.

```
let tapAnyWhere: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(closeKeyboard))
self.view.addGestureRecognizer(tapAnyWhere)
```

I just remove that line, but i lost hide keyboard feature when screen tap :(

**Comment by csericksantos** [comment]
Hi @black-lotus. Know it been a long time but you just need to add:
`tapAnyWhere.cancelsTouchesInView = false`
