### ISSUE TITLE
Add underline for Custom type

### ISSUE THREAD

**Issue by borut-t** [optonaut/ActiveLabel.swift#104]
Is there a way to apply custom attributes for custom types like it's done in TTTAttributedLabel ?

**Comment by poolqf** [comment]
What do you mean by custom attributes? Could you please put an example?

**Comment by borut-t** [comment]
I would like to have custom attribute (not link attribue) with underline style.

**Comment by aldrich** [comment]
A way to have web links show up underlined (or otherwise made to look different from non-links) would be nice, I agree.

**Comment by poolqf** [comment]
We don't have support for underline ATM, but would be happy to receive a PR with it
