### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by alsopgroupinc** [optonaut/ActiveLabel.swift#110]
Great module, love it.  Would love it more if you post a version for Swift 3.   :)

**Comment by poolqf** [comment]
You can take a look at [`swift-3.0`](https://github.com/optonaut/ActiveLabel.swift/tree/swift-3) branch

**Comment by yoshiboarder** [comment]
@poolqf  How do I use swift-3.0 branch using cocoa pod?

**Comment by poolqf** [comment]
Take a lot [here](https://github.com/optonaut/ActiveLabel.swift/issues/113#issuecomment-247599099)
