### ISSUE TITLE
AttributedText issue in the latest version

### ISSUE THREAD

**Issue by MarvinNazari** [optonaut/ActiveLabel.swift#111]
Hi i just updated to the latest version and found a problem with the `attributedText` that if i append an attributedLabel, it gets  attributes of the first one! this didn't happen in 0.6.1 

```swift
contentLabel.customize { label in
    label.numberOfLines = 0
    label.lineSpacing = 4
    label.textColor = UIColor(rgba: "#414548")
    label.font = UIFont.systemFontOfSize(14)
}
let userAttributed = name.attributedMutable(GlobalStyle.Cells.activityUserAttr)
userAttributed.appendAttributedString(" \(activity.text). ".attributed(GlobalStyle.Cells.activityContentAttr))
userAttributed.appendAttributedString(activity.timestamp.shortStringForComment.attributed(GlobalStyle.Cells.activityTimeAttr))
contentLabel.attributedText = userAttributed
```
### and this is what i get in 0.6.1
![screen shot 2016-09-15 at 16 47 12](https://cloud.githubusercontent.com/assets/926772/18554579/ee9b0b0c-7b64-11e6-928c-b3a8ff0dfc53.jpg)

### this is what i get in 0.6.2
![screen shot 2016-09-15 at 17 08 44](https://cloud.githubusercontent.com/assets/926772/18555170/284b5bd4-7b67-11e6-8f78-c776a4e27827.jpg)

**Comment by yoshiboarder** [comment]
@MarvinNazari I had changed swift3 from andreaperizzato's fork.

https://github.com/yoshiboarder/ActiveLabel.swift

It will be working fine in your projects

**Comment by poolqf** [comment]
@yoshiboarder if you have a fix for that, I would be happy if you open a PR 😄

**Comment by davidseek** [comment]
any news on the attributed text issue?

**Comment by phuocmobytelab** [comment]
any fix now?

**Comment by Sejmet** [comment]
AND?
