### ISSUE TITLE
xcode 8 has problem to use ActiveLabel 0.6.2 

### ISSUE THREAD

**Issue by yoshiboarder** [optonaut/ActiveLabel.swift#113]
Hi I'm using the storyboard.

I got an error like this.

file:///Users/test_ios9/test/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for FeedVC (EIx-SL-E27): dlopen(ActiveLabel.framework, 1): Symbol not found: __TMPVs19DictionaryGenerator
  Referenced from: ActiveLabel.framework
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Overlays/../../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in ActiveLabel.framework

Anyone know about this problem?

My Xcode version is 8 and I had convert to swift 2.3.

**Comment by dimovskidamjan** [comment]
I'm seeing the same errors, while using the swift-2.3 branch.

**Comment by assisjeferson** [comment]
@dimovskidamjan exists a pod version with swift 2.3?

**Comment by dimovskidamjan** [comment]
@assisjeferson Yeah, I used this branch: https://github.com/optonaut/ActiveLabel.swift/tree/swift-2.3
It's not merged yet, but you can point to it like this:
`pod 'ActiveLabel', :git => 'https://github.com/optonaut/ActiveLabel.swift.git', :branch => 'swift-2.3'`

**Comment by yoshiboarder** [comment]
@dimovskidamjan Did you solve this problem? If so Could you share?

**Comment by poolqf** [comment]
Hi everyone, does pointing to the correct branch fixes the problem? @dimovskidamjan @yoshiboarder

**Comment by dimovskidamjan** [comment]
No, it does not. The problem goes away on it's own after cleaning and re-building the project and reopening Xcode a couple of times, but it tends to show up again from time to time.

**Comment by poolqf** [comment]
Hi @dimovskidamjan @yoshiboarder @assisjeferson , both master (with Swift 3) and `swift-2.3` branches have been updated. Please check it, and tell me if you still see the issue

**Comment by leminhtuan2015** [comment]
Same for me, So many error on Swift 3

Please fix

**Comment by poolqf** [comment]
Please, if you are not specific, I cannot help. Provide more information

**Comment by leminhtuan2015** [comment]
@poolqf Please help me!

- After I use pod to install your lib, I build project with Xcode 8 and swift 3, I got the below errors

So thank you alot!

![screen shot 2016-10-17 at 9 24 09 am](https://cloud.githubusercontent.com/assets/4700102/19423544/93d5cc16-944b-11e6-8db8-052e7ff65984.png)



![screen shot 2016-10-17 at 9 23 38 am](https://cloud.githubusercontent.com/assets/4700102/19423546/9bbb4ed8-944b-11e6-8cec-586afc931e0e.png)

**Comment by poolqf** [comment]
For what I see, you are not using the last version on `master`. Please check.

**Comment by leminhtuan2015** [comment]
Here is my podfile, Please tell my what version should I import. Thank you!!
```pod
platform :ios, '9.0'

use_frameworks!
target 'DemoLable' do

  #pod 'ActiveLabel'

end
```

**Comment by poolqf** [comment]
Podfile seems ok, what's in your Podfile.lock?

**Comment by dimovskidamjan** [comment]
@leminhtuan2015  I had an issue where `pod update` installed only version 0.6.2 of this repo. Please try running `pod repo update --verbose` and only after it finishes run `pod update`. That way you should get version 0.7.0.

**Comment by dimovskidamjan** [comment]
@poolqf All the warning and errors are now fixed. Good job!

**Comment by cuongdd** [comment]
Please Help Me  - Swift 2.3
![screen shot 2016-10-17 at 4 34 02 pm](https://cloud.githubusercontent.com/assets/9923650/19432770/287d0c08-9488-11e6-969b-18bb88ca1b12.png)
Thank a lot!

**Comment by leminhtuan2015** [comment]
@dimovskidamjan  @poolqf Thank you guys so much, After use version 0.7.0 it work so great.!!!!!

**Comment by poolqf** [comment]
I'm glad you managed to solve your issues. Closing this issue

@cuongdd please use `swift-2.3` branch

**Comment by cuongdd169** [comment]
@poolqf: I used swift-2.3 branch 0.7.0 (Xcode cleaned). But it have error:  
...Main.storyboard: error: IB Designables: Failed to update auto layout status: dlopen(ActiveLabel.framework, 1): Symbol not found: __TMPVs19DictionaryGenerator
  Referenced from: ActiveLabel.framework
  Expected in: /Applications/Xcode 8.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Overlays/../../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in ActiveLabel.framework
. Can you help me. Thank a lot!

**Comment by demonar** [comment]
problem might be related to: https://github.com/CocoaPods/CocoaPods/issues/5334, it's a problem with cocoapods
