### ISSUE TITLE
detection for Mentions with format @facebook.com/sun

### ISSUE THREAD

**Issue by tanujtak1986** [optonaut/ActiveLabel.swift#115]
Hi,  I have some facebook mentions in the format : @facebook.com/tagWord1-tagWord2  (eg : @facebook.com/surf-sunnies)

For mentions in this format, the complete string is not detectable as one. The tap is only detected on "facebook" word.

Can someone please help out with this, or if you can let me know what changes to make in the .mention regex, it'll be helpful.
I have added the files manually.

**Comment by poolqf** [comment]
You could use the `Custom` type to pass a custom regex for that, and disable the default `Mentions` type

**Comment by tanujtak1986** [comment]
Thanks for the input. Will try.

**Comment by poolqf** [comment]
I'll close it for now, feel free to open the issue if the solution I gave you does not help
