### ISSUE TITLE
How do I set bold? 

### ISSUE THREAD

**Issue by yoshiboarder** [optonaut/ActiveLabel.swift#118]
I'm trying to set bold using attributed text.

But Font size has bug. 

Is there anyway to set bold via attributed text?

And When Is updated swift 3.0?

**Comment by poolqf** [comment]
Please, before opening an issue, take a look at open issues and PRs.

PR for custom font: https://github.com/optonaut/ActiveLabel.swift/pull/117
Branch for Swift 3.0: `swift-3.0`

**Comment by yoshiboarder** [comment]
useDifferentHighlightFont means bold?

**Comment by poolqf** [comment]
`Different font for mention, highlight and URLs.`

**Comment by Abdul-Moiz** [comment]
@yoshiboarder useDifferentHighlightFont is a check which causes active label to use a different font for mention, highlight and links.
You need to set highlightfontSize and highlightfontName property in Xcode interface builder.
It will do the trick.

**Comment by poolqf** [comment]
Please, see PR to keep up to date, previous comment from @Abdul-Moiz is outdated

**Comment by yoshiboarder** [comment]
I solved this problem

I just forked @andreaperizzato 
https://github.com/andreaperizzato/ActiveLabel.swift/tree/attributed-text

And convert swift 3.0 in https://github.com/yoshiboarder/ActiveLabel.swift

It works fine. I hope your library embedded in @andreaperizzato 's code.
