### ISSUE TITLE
Hashtag not recognized when leading character is not a whitespace

### ISSUE THREAD

**Issue by peralmq** [optonaut/ActiveLabel.swift#120]
First off, thanks for a great project, it has helped us a lot!

We ran into something that to use i strange behavior around recognizing hashtags. A user in our app posted the following text `"Instagram, L or R?🌟#happyweekend"` that we would have assumed would trigger the hashtag detection and made the text follwing the `#` tapable.. but it turns out that ActiveLabel doesn't recognize it as a hashtag. For us this is strange, for you maybe it is "works as intended".. I'll leave that decision to.

If agree that it was indeed strange then the reason why the hashtag isn't recognized is due to your regex for detecting hashtags. You use `(?:^|\\s|$)#[\\p{L}0-9_]*` from [here](https://github.com/optonaut/ActiveLabel.swift/blob/f6dbed0a91ae01fe13d4b42e5c04195031028585/ActiveLabel/RegexParser.swift#L13) (btw is the `$` here meaning end of line.. then isn't that kinda strange to have that in the non-capturing group?). As you can see the `\\s` means that if the hashtag isn't the first text in the string then it needs a leading whitespace character. 

We just use this `"#[\\p{L}\\d]+"` internally to recognize hashtags in other places and it has worked quite well to us.. maybe you want to switch too?

**Comment by poolqf** [comment]
First of all, thank you for the nice words about the project.

As for the regex, we decided that mentions and hashtags should only be detected when they are the first character of a "word". That said, I get your point, and I think ActiveLabel has a solution that could fit.

You can define the [`enabledTypes`](https://github.com/optonaut/ActiveLabel.swift/blob/master/ActiveLabel/ActiveLabel.swift#L23) that you want the label to recognise. You could remove .Hashtag from the list, and create a .Custom type, where you can pass the desired regex (take a look [here](https://github.com/optonaut/ActiveLabel.swift#custom-types) for more information)

I hope this answer helps. If not, feel free to reopen the issue

**Comment by peralmq** [comment]
Thanks @poolqf that helps!

**Comment by pareekkhushboo77** [comment]
@peralmq , Hi if you have found a custom regex for your issue, please share

**Comment by peralmq** [comment]
@pareekkhushboo77 we use `(?i)#[\\p{L}\\d]+` and implemented it in Swift like this:

```swift
import ActiveLabel

extension ActiveLabel {
    struct CustomActiveTypes {
        static let hashtag: ActiveType = ActiveType.custom(pattern: "(?i)#[\\p{L}\\d]+")
        static let mention: ActiveType = ActiveType.custom(pattern: "(?i)@[a-z0-9_-]+")
        static let url: ActiveType = ActiveType.custom(pattern: "(?i)(https?://)*[-a-zA-Z0-9@:%._\\+~#=]{2,256}\\.[a-z]{2,6}\\b(?=$|[\\s',\\|\\(\\).:;?\\-\\[\\]>\\)])")
    }
}

```

and

```swift
    let commentLabel = ActiveLabel().then {
        $0.enabledTypes = [ActiveLabel.CustomActiveTypes.hashtag, ActiveLabel.CustomActiveTypes.mention, ActiveLabel.CustomActiveTypes.url]
        $0.isUserInteractionEnabled = true
        $0.customColor[ActiveLabel.CustomActiveTypes.hashtag] = UIColor(named: .primaryRedDark)
        $0.customColor[ActiveLabel.CustomActiveTypes.mention] = UIColor(named: .primaryRedDark)
        $0.customColor[ActiveLabel.CustomActiveTypes.url] = UIColor(named: .primaryRedDark)
    }
```
