### ISSUE TITLE
using ActiveLabel in a cell row w/ touch recognizer

### ISSUE THREAD

**Issue by juanjold** [optonaut/ActiveLabel.swift#121]
I'm trying to use the label inside a cell in a UITableView. The cell already has a long-press touch recognizer to report inappropriate content and a touch-recognizer on the cell to open a person's profile. Can the active label be put inside a cell that already has touch recognizers capturing the tap? I've looked everywhere on here to but couldn't find anything! Thanks!!

**Comment by poolqf** [comment]
Yo can have tap gestures on the cell. But all the taps inside the ActiveLabel frame will be captured by the label.
