### ISSUE TITLE
empty string case: sizeToFit() is not working.

### ISSUE THREAD

**Issue by ShawnBaek** [optonaut/ActiveLabel.swift#123]
In case of the label has no strings then sizeToFit() is not working.

I means after sizeToFit() then label's height should be returned 0 but It was returned 1 lines of height.

**Comment by MehulSojitra16** [comment]
Same issue here.

**Comment by freaqed** [comment]
Faced the same issue. In case of empty (or nil) string `intrinsicContentSize` calculated as `(0.0, 14.0)`. In a case of using `UITableView` with dynamic sizing cells look awful.
Any updates here?
