### ISSUE TITLE
touchesCancelled Method does not override any method from its superclass

### ISSUE THREAD

**Issue by jendaz** [optonaut/ActiveLabel.swift#124]
I'm using swift 2.3 branch on Xcode 7 and this error is there for touchesCancelled
ActiveLabel.swift:416: Method does not override any method from its superclass

**Comment by poolqf** [comment]
This should be fixed with the latest changes on `swift-2.3`. Please check if you have the latest ones.

**Comment by jendaz** [comment]
I got that with cocoapods pod 'ActiveLabel', :git => 'https://github.com/optonaut/ActiveLabel.swift.git', :branch => 'swift-2.3' So it should be the latest

**Comment by poolqf** [comment]
I am not receiving this error when compiling `swift-2.3`

Could you please do a `pod update`? Seems like your CocoaPods master repo is not in sync with origin
