### ISSUE TITLE
custom type should override others behavior

### ISSUE THREAD

**Issue by jendaz** [optonaut/ActiveLabel.swift#125]
I set up custom type with:
`ActiveType.Custom(pattern: "\\s#date\\b")`
![cutom-hashtag-ok](https://cloud.githubusercontent.com/assets/8435946/19517489/d46298f6-9601-11e6-831b-eafc0ec98f9d.png)
So the colors are good.
I set selected colors for all tags as the same color only with alpha 0.5. Then the selected color for my custom tag is same like pro regular hashtag
`label.customColor = [customType: UIColor.keyAppGreyColor()]`
`label.customSelectedColor = [customType: UIColor.keyAppGreyColor().colorWithAlphaComponent(0.5)]`
![custom-hashtag-selected](https://cloud.githubusercontent.com/assets/8435946/19517526/fff9b288-9601-11e6-9388-bce2e7cd487d.png)
But the worst thing is that also the regular hashtag handler is called.

So I thing the custom type should have a priority.

**Comment by poolqf** [comment]
You can disable hasthag hightlight if that's the problem

**Comment by jendaz** [comment]
That is the thing. I need also regular hashtags but I have special hashtags let's say #dateToday and I need that for another functionality and with different color.

**Comment by poolqf** [comment]
Hm, ok! I think I have an idea for that. I'll try to work on it when I have time

**Comment by jendaz** [comment]
Maybe I found the solution. This should prioritize types in order of `enabledTypes`. If something intersects already added element it will be removed. It is working for my purpose quite good.

```
/// use regex check all link ranges
    fileprivate func parseTextAndExtractActiveElements(_ attrString: NSAttributedString) -> String {
        var textString = attrString.string
        var textLength = textString.utf16.count
        var textRange = NSRange(location: 0, length: textLength)

        var addedElements = [ElementTuple]()
        
        if enabledTypes.contains(.url) {
            let tuple = ActiveBuilder.createURLElements(from: textString, range: textRange, maximumLenght: urlMaximumLength)
            let urlElements = tuple.0
            let finalText = tuple.1
            textString = finalText
            textLength = textString.utf16.count
            textRange = NSRange(location: 0, length: textLength)
            activeElements[.url] = urlElements
            
            addedElements.append(contentsOf: urlElements)
        }
        
        for type in enabledTypes where type != .url {
            var filter: ((String) -> Bool)? = nil
            if type == .mention {
                filter = mentionFilterPredicate
            } else if type == .hashtag {
                filter = hashtagFilterPredicate
            }
            var hashtagElements = ActiveBuilder.createElements(type: type, from: textString, range: textRange, filterPredicate: filter)
            
            //filter already added elements
            for (i, hashElement) in hashtagElements.enumerated().reversed() {
                if let _ = addedElements.index(where: { (element) -> Bool in
                    let intersection = NSIntersectionRange(element.range, hashElement.range)
                    return intersection.length != 0
                }) {
                    hashtagElements.remove(at: i)
                }
            }
            
            activeElements[type] = hashtagElements
            addedElements.append(contentsOf: hashtagElements)
        }

        return textString
    }
```
