### ISSUE TITLE
Incorrect selected rect

### ISSUE THREAD

**Issue by cruisediary** [optonaut/ActiveLabel.swift#126]
I love this framework

but unfortunately i found somthing like bug

this is simple project 

environment
- Xcode8
- swift 3
- activeLabel 0.7.0

just set hashtag normal and selected color , mentiontag normal and selected color

and set text to `"#1234\n#1234\n#5678\n@asdf\n\n\n#asdfa\n#asdfasdf\n\n"`

<img width="656" alt="screen shot 2016-10-21 at 4 27 26 pm" src="https://cloud.githubusercontent.com/assets/2609775/19590162/65945f30-97ab-11e6-9d6d-cb37b3e9a38d.png">

<img width="435" alt="screen shot 2016-10-21 at 4 24 29 pm" src="https://cloud.githubusercontent.com/assets/2609775/19590115/21165728-97ab-11e6-9920-c85075c67372.png">
<img width="435" alt="screen shot 2016-10-21 at 4 25 10 pm" src="https://cloud.githubusercontent.com/assets/2609775/19590118/2478b2c6-97ab-11e6-874a-5119d5dfa11a.png">

problem is before tag selected when i touch empty rect 

is this duplicated problem, how can i fix it :)

**Comment by poolqf** [comment]
This is a known problem, but haven't find a solution for it

**Comment by cruisediary** [comment]
How about adding pattern like '\s' to solve this problem
that pattern cause event but do nothing, not changing selected color
and hash, mention, url patterns should not affected same to `complementary set`

but this patterns can't solve last sentense cause this problem, must be adjusted
if last sentence of activeLabel fully filled the labels's empty rect then doesn't need to add space char
but if can add space and doesn't change label's height, add space to match above pattern 

1. Add '\s' patterns to delegate empty rect selected event without selectedColor
2. If last sentence is too short fill empty rect then add space char to match '\s' patterns

Is this way can solve this problem and moreover attributedText problem?

**Comment by poolqf** [comment]
Hi @cruisediary I don't quite get what you are saying is good workaround.

If you think that you have a good solution, I would be really have to receive a PR

**Comment by JordanMcCulloch** [comment]
The solution is in the ActiveLabel.swift `element(at location: CGPoint)` method. The index was capturing one too many characters (which could include whitespace). 

Simply add '-1' to `if index >= element.range.location && index <= element.range.location + element.range.length-1`.
