### ISSUE TITLE
Swift Compile Error

### ISSUE THREAD

**Issue by ryandailey100** [optonaut/ActiveLabel.swift#127]
Once i installed the pod and opened up the workspace, I get 63 errors coming from this framework.
<img width="1410" alt="screen shot 2016-10-22 at 10 22 51 am" src="https://cloud.githubusercontent.com/assets/15038444/19620001/85ff011c-9841-11e6-9669-c448f982fcda.png">

**Comment by ryandailey100** [comment]
Just realized I was on the older version. Works now that i am on 0.7.0. Had to use this for it to install the latest version: 
pod 'ActiveLabel', :git => 'https://github.com/optonaut/ActiveLabel.swift.git', :tag => '0.7.0'

**Comment by poolqf** [comment]
Glad you found the solution
