### ISSUE TITLE
Retrieving a list/array of mentions

### ISSUE THREAD

**Issue by ryandailey100** [optonaut/ActiveLabel.swift#129]
Is there a way to get a list/array of mentions or hashtags in the label?

**Comment by poolqf** [comment]
It is not possible ATM, but feel free to open a PR to allow it. You just need to look up/filter (take a look here: https://github.com/optonaut/ActiveLabel.swift/blob/master/ActiveLabel/ActiveLabel.swift#L220)

**Comment by ryandailey100** [comment]
I've been trying to find a way to do this based on what you suggested but no luck. How can I get the text of the elements inside the activeElements variable?

**Comment by poolqf** [comment]
Each element has an [ElementTuple](https://github.com/optonaut/ActiveLabel.swift/blob/master/ActiveLabel/ActiveLabel.swift#L17) and each of those has an [ActiveElement](https://github.com/optonaut/ActiveLabel.swift/blob/master/ActiveLabel/ActiveType.swift#L11)

**Comment by ryandailey100** [comment]
Sorry but I still don't know how to access the text from there. I do not understand how it works

**Comment by ryandailey100** [comment]
<img width="286" alt="screen shot 2016-10-25 at 5 29 49 pm" src="https://cloud.githubusercontent.com/assets/15038444/19705098/b7da265a-9ad8-11e6-8925-2c33f6419f85.png">

This is what I got so far, but it prints in this format: mention("MentionHere")

How can I get rid of the mention("") ?  I only want it to return the mention text.

**Comment by poolqf** [comment]
Unwrap the string associated to the case

**Comment by ryandailey100** [comment]
How do I go about doing that? Cant seem to get it working

**Comment by poolqf** [comment]
I hope this helps

```swift
        for (_, elements) in activeElements {
            for (_, element, _) in elements {
                switch element {
                case .mention(let mention):
                    print(mention)
                case .hashtag(let hashtag):
                    print(hashtag)
                case .url(let originalURL, _):
                    print(originalURL)
                case .custom(let element):
                    print(element)
                }
            }
        }

```

**Comment by ryandailey100** [comment]
Works great thanks!! I opened up a PR for the change.
