### ISSUE TITLE
ConfigureLinkAttributes not available in v0.7?

### ISSUE THREAD

**Issue by rkittinger** [optonaut/ActiveLabel.swift#135]
Using swift 3, custom types seem to be ignored. Using pattern \\ssomeword \\b

**Comment by rkittinger** [comment]
pod install doesn't install the version in master

**Comment by poolqf** [comment]
The `pattern` you pass in is treated as a Regular Expression. So there's probably something wrong with it 🤔

**Comment by poolqf** [comment]
Also, adding new custom types does not update the label ATM. Please check that
