### ISSUE TITLE
Font for highlight 

### ISSUE THREAD

**Issue by Jellyfishinatrifle** [optonaut/ActiveLabel.swift#136]
Hi is it possible to specify a particular font for a highlighted word? Similar to mentionColour on the api... is there a mentionFont or some way of achieving this? 

I attempted to just add the font into the attributes in addLinkAttribute() but I think there may be an issue with using different fonts as I see extra vertical spacing.

Any info would be hugely appreciated. Thanks. Jules

**Comment by poolqf** [comment]
Whenever https://github.com/optonaut/ActiveLabel.swift/pull/122 is merged, you'll be able to do it
