### ISSUE TITLE
Umbrella header 'ActiveLabel-umbrella.h' not found

### ISSUE THREAD

**Issue by viktorwillmann** [optonaut/ActiveLabel.swift#137]
this happens suddenly. I did work for a time but now it does not. I am using the Mainbranch, cocoa pods 1.1.1 and Swift 3.

**Comment by poolqf** [comment]
What's in your Podfile? Are you opening the xcworkspace?

**Comment by JPROFFICIAL** [comment]
Hey @poolqf I can +1 this. `module ActiveLabel.Swift {
    header "ActiveLabel-Swift.h"
}
`
which in turn doesn't let me import `ActiveLabel`

Any fix? I am using the latest version on the master branch

**Comment by viktorwillmann** [comment]
@poolqf  pod 'ActiveLabel', yes i always used xcworkspace. 
@JPROFFICIAL 
i imported the code directly without cocoa pods, that made it work.
