### ISSUE TITLE
ActiveType.custom not working with some word

### ISSUE THREAD

**Issue by albarq** [optonaut/ActiveLabel.swift#138]
HI, 

I am suffering from an issue with acticeType custome:

This one is NOT working
        let PrivacyPolicy = ActiveType.custom(pattern: "\\Privacy Policy\\b")
This one is working:
        let PrivacyPolicy = ActiveType.custom(pattern: "\\Trivacy Policy\\b")

        label.text = "By signing up, you agree to the Terms of Service and Privacy Policy including Cookie use."

any help?

**Comment by poolqf** [comment]
The `pattern` you pass in is treated as a Regular Expression. So there's probably something wrong with it 🤔

**Comment by stefanomondino** [comment]
shouldn't that be `ActiveType.custom(pattern: "\\sPrivacy Policy\\b")`?

**Comment by albarq** [comment]
True  ,,, = ActiveType.custom(pattern: "\\bPrivacy Policy\\b")  is working .. thank you

**Comment by choioi** [comment]
"\\b(View sample)\\b" not working.. only "View sample" change color.., "(" and ")" is not.

**Comment by albarq** [comment]
Have you tried "\b\(View sample\)\b"

**Comment by 1xiaocainiao** [comment]
I tried ActiveType.custom(pattern: "\\b《隐私协议》\\b")， but it still doesn't work
