### ISSUE TITLE
Delay when tapping on active element.

### ISSUE THREAD

**Issue by anatoliyv** [optonaut/ActiveLabel.swift#139]
I'm seeing next problem on a device (iOS10). On simulator all works fine. When tap on active element  takes less than 2 seconds touch got `cancelled` event and as a result no handlers are being called. When it takes more than 2 seconds everything is fine. Is there a way to shorten this time period?

**Comment by anatoliyv** [comment]
It was my mistake. Reason was my superview contains own gesture recognizer that conflicts with ActiveLabel events. Closing, not an issue any more...

**Comment by emil622** [comment]
Good catch @anatoliyv , I had the same issue, solved by your comment 👍
