### ISSUE TITLE
Tutorials for Tableview 

### ISSUE THREAD

**Issue by yoshiboarder** [optonaut/ActiveLabel.swift#144]
Hi I like ActiveLabel's features.

But I can't find good example of tableview.

I'm trying to use ActiveLabel in my Custom TabelViewCell but It seems choppy and lagged when scrolling.

Anyone share your tableview examples?

Thanks

**Comment by yoshiboarder** [comment]
I've solved this problem via ActiveLabelDelegate

closed

**Comment by ameli90** [comment]
Hi @ShawnBaek, do you have any hints how to improve TabelView scroll with ActiveLabel?

**Comment by ShawnBaek** [comment]
@ameli90 

Sure. Here is snippet of my code.

//STEP 1. Set ActiveLabelDelegate
class FeedView: UITableViewController, ActiveLabelDelegate {

 //STEP 2. Declare Delegate ActiveLabel Funcion
    public func didSelect(_ text: String, type: ActiveType) {
        switch type {
            
            case .mention:
                alert("Mention", message: text)
            
            case .hashtag:
              alert("Hashtag", message: text)
            

            
            case .url:
                alert("URL", message: text)
                
            default:
                break
        }
        
    }


//STEP 3. set Delegate as Self on ActiveLabel properties
 override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: "DetailCell", for: indexPath) as! DetailCell
  //STEP 4. commentLbl is ActiveLabel 
cell.commentLbl.delegate = self
      
}


}


That's All~!

I hope helping you 👍
