### ISSUE TITLE
.-_ not working in custom types

### ISSUE THREAD

**Issue by ldebna** [optonaut/ActiveLabel.swift#145]
I cant seem to get the mention to bring in a string containing a ., - or a _  it always seems to cut off at these

this is the code I am using:

let customType = ActiveType.Custom(pattern: "(?:^|\\s|$)@[\\p{L}0-9.\\-_]*")
comment.enabledTypes = [customType]
comment.customColor[customType] = Color.blue
comment.handleMentionTap {
  mention in
  guard let userID = self.commentsModel?.tagList[mention] else {
    self.delegate?.taggedUserNotFound()
    return
  }
  self.delegate?.viewProfile(userID, username: mention)
}

**Comment by poolqf** [comment]
Please provide examples of what you want to get out of this. Also, keep in mind that the `pattern` is going to be interpreted as a regex. Maybe it is wrong

**Comment by hdoria** [comment]
Same problem here. I'm trying to match "Read More ...".

What I've tried:

```
let readMoreCustom = ActiveType.custom(pattern: "\\sRead More ...\\b")
let readMoreCustom = ActiveType.custom(pattern: "\\sRead More \\.\\.\\.\\b")
```

**Comment by poolqf** [comment]
Same as I said to @ldebna, the string is treated as a Regex. Try your regex in a playground to see if it is the correct one for what you are trying to match 😄
