### ISSUE TITLE
Custom Type: Unable to set custom type for words, are at initial position in sentence

### ISSUE THREAD

**Issue by krunalbhavsar** [optonaut/ActiveLabel.swift#147]
let username = "Krunal Bhavsar"
        let userCustomType = ActiveType.custom(pattern: "\\s\(username)\\b")

        cell.lblTitle.enabledTypes.append(userCustomType)
        cell.lblTitle.customize { (label) in
            label.text = "\(username), unable to set custom type for words, are at initial position in sentence \(username)"
            label.hashtagColor = UIColor.green
            label.customColor[userCustomType] = UIColor.red 
        }

![screen shot 2017-01-18 at 8 24 48 pm](https://cloud.githubusercontent.com/assets/16011224/22068792/2e8690e2-ddbc-11e6-84a3-9e8cc1696b0a.png)

**Comment by krunalbhavsar** [comment]
This worked for me. :)
 let userCustomType = ActiveType.custom(pattern: "\\\(username)\\b")

**Comment by yutmr** [comment]
@krunalbhavsar Maybe pattern is wrong.
Try `let userCustomType = ActiveType.custom(pattern: "(?:^|\\s|$)\(username)\\b")`.

**Comment by poolqf** [comment]
Please, check that your pattern is correct. Otherwise reopen the issue 😄

**Comment by krunalbhavsar** [comment]
It's working fine! 
It's really nice feature.
Thank you!!!

**Comment by pareekkhushboo77** [comment]
@poolqf , the above pattern doesnt work when my text is : ABC Alpha (P) LTD, Surat, Gujarat, India,
