### ISSUE TITLE
Setting urlMaximumLength revokes access to original complete URL

### ISSUE THREAD

**Issue by dnadri** [optonaut/ActiveLabel.swift#150]
When the length of the URL in an ActiveLabel (i.e.: `label.urlMaximumLength = 30`) is greater than the set `urlMaximumLength`, the original full **url** inside `label.handleURLTap { url in 
...
}` is not available.

Is there a way to trim the URLs in the label while maintaining the original full URL so to open it inside `handleURLTap` such as via `UIApplication.sharedApplication().openURL(url) `?

Currently, tapping on a URL inside an ActiveLabel that trims a URL contained inside it via the `urlMaximumLength` property, leads to an invalid web page when opening the url (i.e. via `openURL`).

**Comment by poolqf** [comment]
Hi @dnadri, I've been checking the issue you are having, and I cannot reproduce it. 
To double check it I just added new tests for that checking the cases when the URL in the label is above and below the limits. You can take a look at them here: https://github.com/optonaut/ActiveLabel.swift/commit/446dbcd9fbc6403aa4434ad8d79eae765b8bff17

If you are still having issues with it, please attach a snippet of code. 😄

**Comment by dnadri** [comment]
@poolqf Thanks for checking out this issue.

Here's a snippet of code inside an ActiveLabel subclass I created:
Let's say inside the label is the following URL (56 characters long):
https://github.com/optonaut/ActiveLabel.swift/issues/150
```
        urlMaximumLength = 30
        customize { label in
            label.enabledTypes = [.URL]
            label.numberOfLines = 0
            label.textColor = UIColor.darkTextColor()
            label.URLColor = UIColor.blueColor()
            label.URLSelectedColor = UIColor.grayColor()
            label.handleURLTap { url in
                print("url: \(url)")
                // prints "https://github.com/optonaut/Ac" (30 characters)
                // trying to open this link would lead to an invalid page
                UIApplication.sharedApplication().openURL(url)
                // it should have access to the original full link (https://github.com/optonaut/ActiveLabel.swift/issues/150) if one decides to open the link inside this block, for example
            }
            
        }
```
Thanks!

**Comment by poolqf** [comment]
I just copy pasted it on the Demo project, and it is working.. 🙃 

I can see you are using Swift 2.3, so maybe there's an issue on that branch. I'll take a look

**Comment by aroyarexs** [comment]
Currently, we have the same error. 
Using the URL `https://github.com/optonaut/ActiveLabel.swift/issues/150` results in the exact same error like @dnadri described.
Here is our code:
```
            label.URLSelectedColor = UIColor.black
            label.urlMaximumLength = 30
            label.handleURLTap({ (url) in
                if url.absoluteString.isValidForUrl() {
                    UIApplication.shared.openURL(url)
                } else if let url = URL(string: "http://" + url.absoluteString) {
                    UIApplication.shared.openURL(url)
                }
            })
```

@poolqf I don't know why but `original` and `trimmed` are both set to the trimmed one.
```
(lldb) po activeElements[.url]
▿ Optional<Array<(range : _NSRange, element : ActiveElement, type : ActiveType)>>
  ▿ some : 1 element
    ▿ 0 : 3 elements
      ▿ range : _NSRange
        - location : 0
        - length : 30
      ▿ element : ActiveElement
        ▿ url : 2 elements
          - original : "https://github.com/optonaut/Ac"
          - trimmed : "https://github.com/optonaut/Ac"
      - type : ActiveLabel.ActiveType.url
```
Breakpoint set inside `didTapStringURL(_ stringURL: String)`.

Cheers,

Aaron

**Comment by aroyarexs** [comment]
Sorry, we misused `label.text`.
We assigned `label.text` to a new variable, altered the variable, and assigned the variable to `label.text`.
This causes the problem since `label.text` already contains the trimmed url.

@dnadri May be this is also your error?!
