### ISSUE TITLE
Index of ActiveLabel Pattern pressed.

### ISSUE THREAD

**Issue by nitesh-ios** [optonaut/ActiveLabel.swift#156]
Is there any way I get index of which exactly Label is pressed.
I'm using mention tap I.e username and when user click on it I need userID of that user and not username. So in this case if I get the index of which username is pressed then I could fetch the userID easily.

**Comment by pushkardeshmukh1992** [comment]
I am looking for something similar! Have you achieved same @nitesh-ios ?

**Comment by pushkardeshmukh1992** [comment]
Any update on this?

**Comment by maziyarpanahi** [comment]
Sorry there is no such thing as returning index. In this case every fucntion returns the value of the label which there you should either look into your data to find more info or use and API to query something.
I suggest using the same array which you load your TabeView with to find out other details about what just being pressed.
