### ISSUE TITLE
It needs 5s to get the action

### ISSUE THREAD

**Issue by remlostime** [optonaut/ActiveLabel.swift#158]
It takes me 5s to tap hash tag or name tag to trigger the touch action. Otherwise, there is no response. Don't know why?

**Comment by chrisdhaan** [comment]
@remlostime are you experiencing this issue within a UITableViewCell? I get the normal response in a plain UIView. But when trying to using the ActiveLabel in a UITableViewCell I am seeing a several second delay. Almost as if it's a long press gesture opposed to a tap.

**Comment by remlostime** [comment]
That's true. It's in cell. Do you have idea how to fix it? @chrisdhaan

**Comment by chrisdhaan** [comment]
@remlostime I have no found a solution yet and spent almost an entire day looking for one. @poolqf is this behavior that you experience when running Active Label in a UITableViewCell?

**Comment by decoyfox** [comment]
@chrisdhaan @remlostime You can fix this using:

> tap.cancelsTouchesInView = false

For example I have a gesture on my entire view, but the above line will pass the touch through to the ActiveLabel, and should work!

```
let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(CommentsViewController.dismissKeyboard))
        
tap.cancelsTouchesInView = false
        
view.addGestureRecognizer(tap)
```
