### ISSUE TITLE
Passing extra data to custom ActiveType

### ISSUE THREAD

**Issue by jovanpreet** [optonaut/ActiveLabel.swift#159]
I am using ActiveLabel in UICollectionView cells. The types are custom. The didSelect only returns the text and ActiveType. What i need is to attach some kind of id with each custom activeType. So i can differentiate between two different type with same text but are on different cells. 
Or if we can get the indexPath of the tappable text.
Any help is highly appreciated

**Comment by pareekkhushboo77** [comment]
You can use following code :
On Tap you will receive the text + tag (which is the row tapped)

let customType = ActiveType.custom(pattern: "(?:^|\\s|$)with\\b") //Regex that looks for "with"
        label.enabledTypes = [customType]
        label.tag = indexpath.row
        label.customColor[customType] = UIColor.purple
        label.customSelectedColor[customType] = UIColor.purple
        label.handleCustomTap(for: customType) { element in
            print("Custom type tapped: \(element)")
            print("Tapped tag : ",label.tag)
        }

**Comment by jovanpreet** [comment]
Tag is really not reliable with batchUpdates of collectionView because when we insert 2 rows then the initial row at indexPath.item = 0 and indexPath.item = 2 will have same tag as tag doesn't get updated on insertions.
