### ISSUE TITLE
Working with UIScrollView

### ISSUE THREAD

**Issue by jdriselvato** [optonaut/ActiveLabel.swift#16]
I'm having issues getting this working with UIScrollViews. UIScrollView doesn't seem to allow for interaction with the linking.

**Comment by jdriselvato** [comment]
My issue seems to be a problem with UIViews with ActiveLabels on it inside a UIScrollView. Not a problem with this specifically.

**Comment by schickling** [comment]
Glad to hear this could be resolved.

**Comment by bogdanh** [comment]
Hi @jdriselvato,

I know it's kind of old but how you managed to fix the problem with ActiveLabels inside a UIScrollView? I have the same problem now. It is working well when the ActiveLabel is not within an UIScrollView but not when it's within. I tested with other UILabel elements and the tap is working.

Any answer will be much appreciated. Thank you.

**Comment by croossin** [comment]
@jdriselvato  or @bogdanh  Were you able to find a solution to this problem?

**Comment by lindlau** [comment]
same problem here

**Comment by jdriselvato** [comment]
If I remember correctly, what I ended up doing was subclassing a UITableViewCell instead of using scroll view and views to fix my problem. Sorry, I know that's not what you want to hear but it worked out for the project I was working on (2 years ago).
