### ISSUE TITLE
Bug when set attribute text underline

### ISSUE THREAD

**Issue by chungbkhn** [optonaut/ActiveLabel.swift#160]
I tried to add attribute text has attribute underline (a part of text) like this:

> let content = "Hello TableView"

        let att = NSAttributedString(string: "TableView", attributes: [NSUnderlineStyleAttributeName: NSUnderlineStyle.styleSingle.rawValue])
        let attributedText = NSMutableAttributedString(string: "Hello ")
        attributedText.append(att)

        lblTitle.attributedText = attributedText

But on UI, label display underline for fulltext.

**Comment by manishsharma31** [comment]
sampel problem with us... please reply
