### ISSUE TITLE
HTML Support

### ISSUE THREAD

**Issue by n1tesh** [optonaut/ActiveLabel.swift#162]
Is it possible to use NSAttributedString which supports the HTML.

**Comment by r-a-o** [comment]
Need HTML support for the label. 

Can we have a link parser when label's `activeLabel.attributedText` is set to a string with `<a>` tags?
Not every text we use will be a direct url of format `http://`, we need support for html `a` tags.

**Comment by techmehra** [comment]
HTML Support

**Comment by AkshayBorale** [comment]
facing same problem , if  Label contain multiple html tags its not worked properly. some tags not getting applied like bold italic, color  text etc...
