### ISSUE TITLE
Hashtag ignore first and single character

### ISSUE THREAD

**Issue by fumitoito** [optonaut/ActiveLabel.swift#166]
Hi, I found that first and single character for hashtags is ignored (e.g. `#1 foo bar` is not highlighted).
Why ActiveLabel ignore that ? It happens at not only single numbers but also single KANJI.

e.g. 1. Single numbers

![single_character](https://cloud.githubusercontent.com/assets/770377/24866845/642d9284-1e46-11e7-9a58-9e36a824ff1f.png)

e.g. 2. Single KANJI

![single_kanji_character](https://cloud.githubusercontent.com/assets/770377/24866844/62ec2e30-1e46-11e7-9008-0aa50ebd43a8.png)

**Comment by pareekkhushboo77** [comment]
Please check issue no #120

**Comment by fumitoito** [comment]
@pareekkhushboo77 thanks for your reply. Do you mean "1" is NOT a "word" (#120) and "桜" is not supported language (#2) ?

**Comment by pareekkhushboo77** [comment]
No, that means it doesn't check for leading character, that why "1" is not recognised, you can change the pattern as given in #120 , or even make your custom pattern. 
Or please check keeping "#1" in between, and check whether its recognised or not.

**Comment by fumitoito** [comment]
ok I can understand and fix my problem. Thanks @pareekkhushboo77 !
