### ISSUE TITLE
Error while casting label as ActiveLabel with Interface Builder

### ISSUE THREAD

**Issue by sebastienboulogne** [optonaut/ActiveLabel.swift#168]
Hello, i would like to create a label with Interface Builder and cast it as ActiveLabel
(ex : @IBOutlet weak var postMessageCell: ActiveLabel!
)
I set ActiveLabel class as a custom class for the label but i've got this error from Xcode : Use of undeclared type 'ActiveLabel'.

So how to create a simple label with Interface Builder and cast it as an Active Label ?

Thank you

**Comment by askopin** [comment]
use field "module" under class name in IB to point where xcode should search for your class
