### ISSUE TITLE
Facing issue for any first words custom type attributed string

### ISSUE THREAD

**Issue by PratikHyperlink** [optonaut/ActiveLabel.swift#177]
Facing issue for any first words custom type attributed string. Custom attributed text not working for first words. For example if "Lorem Ipsum is simply dummy text" then it's not working if "Lorem" word if my text " Lorem Ipsum is simply dummy text" using initial space then same code working for "Lorem" word. 

Please help me.
Thanks in advance.

**Comment by sasojadrovski** [comment]
Hey @PratikHyperlink,

Take a look at [this](https://github.com/optonaut/ActiveLabel.swift/issues/169#issuecomment-301442600) comment. The solution worked for me. 

For your example, the regex would be: `"(?:^|\\s|$)Lorem\\b"`. I hope this helps.

Maybe this should be added to the `README.md`.

**Comment by khush004** [comment]
@sasojadrovski  **"(?:^|\\s|$)Lorem\\b"**  this is not works for me can you please check my code 

        let firstTagName = ActiveType.custom(pattern: "(?:^|\\s|$)\(userName)\\b")
        cell.lblSubject.enabledTypes = [firstTagName]

**Comment by Premal-Khetani** [comment]
@khush004  it's working fine for me. thanks
