### ISSUE TITLE
How to add Bold style to words with hashtags ?

### ISSUE THREAD

**Issue by sebastienboulogne** [optonaut/ActiveLabel.swift#180]
Hi, i would like to bold words with hashtag instead of changing color... How to do it ? Thank you

**Comment by ShawnBaek** [comment]
I had same questions. And I fork the repositories. https://github.com/ShawnBaek/ActiveLabel.swift

**Comment by sebastienboulogne** [comment]
ShawnBaek, how to easily add the Bold style to a hashtag in the native version of ActiveLabel please ? Or how to get your fork version with cocoapod (what to write to my pod file to get your version...) Thank you

**Comment by sebastienboulogne** [comment]
I'm sorry @ShawnBaek  but i really didn't find the stuff i was looking for in your code... What's the simplest way to add bold style to hashtag please ? Can you show me the code please. Thank you so much

**Comment by ShawnBaek** [comment]
@sebastienboulogne 

Sorry for late. Today I received the email from you. I just updated my fork version -> https://github.com/ShawnBaek/ActiveLabel.swift-master-2

It is working fine with Xcode 8.

I have time to remind how to set bold. My tip is you can use attributedText. I will let you know this weekend.

**Comment by sebastienboulogne** [comment]
@ShawnBaek i sent you an email asking for an example please on how to set bold style to a hashtag ;) Thx

**Comment by cikpis** [comment]
Pending PR https://github.com/optonaut/ActiveLabel.swift/pull/192

**Comment by el-quick** [comment]
Please include this feature.
