### ISSUE TITLE
Any way to fire a function whenever a hashtag or custom type is used? 

### ISSUE THREAD

**Issue by hollowaytyl** [optonaut/ActiveLabel.swift#181]
I want to count how many times users use a certain hashtag and word, is there a way for me to fire a function everytime it's used similar to how the code changes hashtag and mention colors? 

Thanks for any help.

**Comment by nsandeep440** [comment]
`let customType = ActiveType.custom(pattern: "\\sTerms and Conditions\\b")
        labelTermsandConditions.enabledTypes = [customType, .url]
        labelTermsandConditions.text = "I agree to Terms and Conditions "
        labelTermsandConditions.customColor[customType] = THEME_COLOR
        labelTermsandConditions.customSelectedColor[customType] = UIColor.green
        labelTermsandConditions.handleCustomTap(for: customType) { element in
            print("Custom type tapped: \(element)")
        
        }`
closure is not called immediatly when tapped, but will triggered if pressed for 1 or 2 seconds. Do anyone can help me in this???

**Comment by thecorsair** [comment]
same problem
