### ISSUE TITLE
Set tap on sentence.

### ISSUE THREAD

**Issue by Rushabh5** [optonaut/ActiveLabel.swift#190]
Hello,

How can i set my label text to create a link with space like, **xyz abc** record updated where **xyz abc** needs to be display as tappable link.

Can you please help me with that?

Thanks in advance!

**Comment by jorge-ramirez** [comment]
I would also like to do the same thing.  I need to link the phrase "Guest Policies" in the sentence: "I have read and agree to the Guest Policies."

Is this possible since it contains spaces?
