### ISSUE TITLE
`handleMentionTap` causing memory leaks although handler removed in `deinit`

### ISSUE THREAD

**Issue by blurtime** [optonaut/ActiveLabel.swift#191]
I am using a `UIPageViewController` containing various `UIViewControllers` containing in turn various `UIElements` as well as one`ActiveLabel`. After integrating the library I started noticing that my app sometimes malfunctioned and certain parts were not working accurately anymore. Shortly afterward, I found that my memory was reaching unusually high levels and began inspecting the it, eventually finding that the reason was the function `handleMentionTap`. (There is still more to read below the first code...)

**My code is the following:**

    lazy var postDescription: ActiveLabel = {
        let entireDescView = ActiveLabel()

        entireDescView.font = UIFont.systemFont(ofSize: 17)
        entireDescView.numberOfLines = 3
        entireDescView.lineBreakMode = NSLineBreakMode.byTruncatingTail
        entireDescView.textColor = .white
        entireDescView.textAlignment = .left
        
        entireDescView.enabledTypes = [.mention]
        entireDescView.mentionColor = UIColor(red: 25/255, green: 153/255, blue: 1, alpha: 1)
        entireDescView.handleMentionTap { hotel in //engendering memory leaks
            self.pushProfileController(of: hotel)
        }
        
        //adding shadow
        let layer = entireDescView.layer
        layer.shadowColor = UIColor.black.cgColor
        layer.shadowOffset = CGSize(width: 1, height: 1)
        layer.shadowRadius = 1
        layer.shadowOpacity = 0.5
        
        return entireDescView
    }()

Accordingly, I reasoned that removing the handle for mention in the `deinit` of the `UIViewController` should somewhat deallocate(?) the function. Unfortunately, this did not work either. Can you explain why this memory leak is occurring and how one could fix it? I would really appreciate your help!

**Here is the code:**

    deinit {
        postDescription.customize({ (descriptionLabel) in
            descriptionLabel.removeHandle(for: .mention)
        })
    }

**Comment by maxmzd** [comment]
I'm having the same problem.

**Comment by blurtime** [comment]
@maxmzd This Memory leak is occurring due to a retain cycle. Use a `weak self` reference and you should be good to go. At least that's what worked for me.

**Comment by maxmzd** [comment]
@blurtime thank you, that helped release the memory.
