### ISSUE TITLE
Swift 4

### ISSUE THREAD

**Issue by Blackjacx** [optonaut/ActiveLabel.swift#197]
How fast can you possible create and maintain a swift4 branch? It is sad that such a popular project does not offer beta updates...

**Comment by ShawnBaek** [comment]
+ I'm going to add ellipse feature.

**Comment by Blackjacx** [comment]
Any new information?

**Comment by kleber11** [comment]
Hey guys. Any updates for Swift 4?

**Comment by james-ff** [comment]
Looks like it just needs a podspec version update? A recent commit seems to add Swift 4 support.

**Comment by tditchek** [comment]
Hi guys. Love ActiveLabel, but any news on updating the podspec to include the Swift 4 commits?

**Comment by Blackjacx** [comment]
Jupp it is just the podspec. Would be nice if you could push this small little update ;-)

**Comment by maziyarpanahi** [comment]
For now I am pointing to 0.8.0 manually: 
`pod 'ActiveLabel', :git => 'https://github.com/optonaut/ActiveLabel.swift.git', :tag => '0.8.0'`

**Comment by petrovi4** [comment]
@maziyarpanahi Not worked for Swift 4 in ObjC project (Cocoapod integration).

**Comment by maziyarpanahi** [comment]
Version 0.8.1 is now available on CocoaPods:
https://cocoapods.org/pods/ActiveLabel
