### ISSUE TITLE
Does not support Chinese

### ISSUE THREAD

**Issue by weifans** [optonaut/ActiveLabel.swift#2]
Thank you develop the library, but does not support Chinese, looked at them, use regular expressions, no modification is successful, I hope you can support the Chinese as soon as possible, thank you.

**Comment by schickling** [comment]
Hi @weiFans. Thanks for reporting this issue. It should be resolved by tackling #1 in the future.

**Comment by Estanque** [comment]
Please fix this issue for Russian language too.

**Comment by mamouneyya** [comment]
Suggestion for the detection regular expression: [\\w\\_]+

**Comment by nanhuo** [comment]
If you only need Chinese and English support, check this https://github.com/nanhuo/ActiveLabel.swift

**Comment by dsinkovskiy** [comment]
Please check my pull request #78. The problem is solved. You can override regex patterns as you wish. And there are some really good regex for hashtags and mantions with multilanguage support in Tests.
