### ISSUE TITLE
Objective-C support?

### ISSUE THREAD

**Issue by danipralea** [optonaut/ActiveLabel.swift#20]

**Comment by schickling** [comment]
Hey @danipralea, since we're using Swift, we didn't had the use-case before to support ObjC.
But please feel free to open up a PR adding ObjC support if there are any additions needed.

**Comment by danipralea** [comment]
Ok, thank you for your reply. I'm not a Swift expert, so I would rather not complicate things. Found another Obj-C library though.

**Comment by schickling** [comment]
Great. Closing this for now.

**Comment by intoxicated** [comment]
@danipralea would you mind to tell me the name of library you found for Objective-C?

**Comment by danipralea** [comment]
@intoxicated It's been a long time since then, but I think I sticked with ActiveLabel. Porting it to Objective-C will result in a pretty good library as well

**Comment by intoxicated** [comment]
@danipralea did you port it to objc yourself? or should I make it my own and maybe share it on the community :)?

**Comment by danipralea** [comment]
no, you can use it directly @intoxicated

**Comment by intoxicated** [comment]
@danipralea what do you mean by use it directly? you mean bridging swift code into objc?

**Comment by danipralea** [comment]
yup

**Comment by intoxicated** [comment]
@danipralea ah i see. Due to application size, I think I'm going to port into Objective-c, in fact, the code itself is not complicated at all. Thanks for quick respond!

**Comment by danipralea** [comment]
glad I could help
