### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by tobias-emmerling** [optonaut/ActiveLabel.swift#205]
When is the Podspec avaible for Version 0.8 i need that soon for my project? I added ActiveLabel as a dependency in my Podspec.

**Comment by audionowdigital** [comment]
Me too, me too!

**Comment by audionowdigital** [comment]
I'm waiting for the same thing.
But I solved it for the moment by specifying the Swift4 commit in the Podfile:

`pod 'ActiveLabel', :git => 'https://github.com/optonaut/ActiveLabel.swift', :commit => '3f869d1' `

**Comment by tobias-emmerling** [comment]
Would work, but the problem is that i cannot set this in the podspec for s.dependency :(

**Comment by yunnnyunnn** [comment]
+1
Currently I am using
`pod 'ActiveLabel', :git => 'https://github.com/optonaut/ActiveLabel.swift.git', :tag => '0.8.0'`
to point to the latest swift 4 release.

**Comment by tobias-emmerling** [comment]
Yes but i need it for s.dependency in my podfile and there i cannot specify a tag

**Comment by maziyarpanahi** [comment]
Version 0.8.1 is now available on CocoaPods:
https://cocoapods.org/pods/ActiveLabel

**Comment by audionowdigital** [comment]
Thank you for contacting the AudioNow Support Team. We're investigating
your issue and will reply as soon as possible.

The AudioNow Team

Case #: 522402782022837

<http://www.audionow.com/>

*AudioNow Support*
* | **http://www.AudioNow.com <http://www.audionow.com/>*
