### ISSUE TITLE
Losing text attachments

### ISSUE THREAD

**Issue by azatZ** [optonaut/ActiveLabel.swift#209]
If you set ActiveLabel attributed string with text attachments they will disappear. It happening because when the label perform 
`let newString = parseTextAndExtractActiveElements(mutAttrString) mutAttrString.mutableString.setString(newString)`
it loses all text attachments in the original attributed string. I think I fixed the issue, I can make pull request, but I want to be sure that it's not expected behaviour.

**Comment by andreaslindahl** [comment]
I'm having this problem as well. Is there a fix?

**Comment by ThoseGuysInTown** [comment]
Also having this problem
