### ISSUE TITLE
@ mention

### ISSUE THREAD

**Issue by RajaReddyIOS** [optonaut/ActiveLabel.swift#210]
If mention people are not available on server database Then how can we handle mention string

**Comment by arnaudlebourblanc** [comment]
@RajaReddyIOS I believe that you are somehow asking your server if the text mentionned correspond to a user and your server is answering you something that tells you if a user with this name exist. The only thing related to the project ActiveLabel here is the fact that you click on a label containing a mention and a block of code you gave is executed. ActiveLabel is no way related to your issue.

But to only answer your question you should alert the user of your app that the user mentionned in the ActiveLabel does not exist.

**Comment by pvcary** [comment]
Hi @arnaudlebourblanc ,

On a semi-related note, can ActiveLabel detect name mentions like @Raja Reddy with a space between the first and last name? Is there something you would recommend doing in this case?

Thanks,
Patrick

**Comment by raja** [comment]
Please don't tag me on issues.

**Comment by pvcary** [comment]
Sorry! ^
