### ISSUE TITLE
the version in cocoapods is still 0.7.1 ?

### ISSUE THREAD

**Issue by ruixingchen** [optonaut/ActiveLabel.swift#211]
and so in the podspec file?

**Comment by sherwinzadeh** [comment]
I made a PR. You can use my fork and it seems to work:
https://github.com/sherwinzadeh/ActiveLabel.swift

**Comment by ruixingchen** [comment]
@sherwinzadeh  thanks, Xcode9 now understands Swift3 codes, the old 0.7.1 version still works good as usual,  just a little tap to tell Xcode this target is using Swift3.2, :P

**Comment by gygreene** [comment]
@ruixingchen How do you do that?

**Comment by JustinBobo** [comment]
@gygreene go to pods, then build settings, then the target for the pod, and change "Swift Language Version" to 3.2. 
<img width="1252" alt="screen shot 2017-10-23 at 11 41 43 pm" src="https://user-images.githubusercontent.com/25378266/31923929-c2212fbe-b84b-11e7-8dcc-d7175a8948d9.png">

**Comment by ruixingchen** [comment]
@gygreene Yes @JustinBobo said is right, but if you had far more pod target than 1, like 10 or more, changing it manually will take a lot time, try this
```
post_install do |installer|
    oldSwiftTargets = ['Toast-Swift', 'StatefulViewController', 'Kanna', 'SwiftyJSON', 'GDPerformanceView-Swift']
    installer.pods_project.targets.each do |target|
        if oldSwiftTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```
just add the block to your podfile, :)

**Comment by gygreene** [comment]
Thanks @JustinBobo  and @ruixingchen! Got it working!

**Comment by maziyarpanahi** [comment]
Version 0.8.1 is now available on CocoaPods:
https://cocoapods.org/pods/ActiveLabel
