### ISSUE TITLE
Active label version 7.0.1 issue when appyling attribute

### ISSUE THREAD

**Issue by manishsharma31** [optonaut/ActiveLabel.swift#213]
I tried to add attribute text has attribute underline (a part of text) like this:

let content = "Hello TableView"
    let att = NSAttributedString(string: "TableView", attributes: [NSUnderlineStyleAttributeName: NSUnderlineStyle.styleSingle.rawValue])
    let attributedText = NSMutableAttributedString(string: "Hello ")
    attributedText.append(att)

    lblTitle.attributedText = attributedText
But on UI, label display underline for fulltext

**Comment by cikpis** [comment]
Same problem here. @manishsharma31 did you manage to solve it?
