### ISSUE TITLE
Swift 4 support to this library  

### ISSUE THREAD

**Issue by shubhamKhelfie** [optonaut/ActiveLabel.swift#216]
when i was trying to pod this in library in xcode 9.0.1, in the pod directory it shows 14 errors.

**Comment by ZacharyKhan** [comment]
According to issue #147 it seems to just be the pod spec that needs updating. I’ll fork the repo and make any updates to conform to latest Swift syntax and submit a PR. it’s really up to @optonaut to accept the request(s).

**Comment by ThoseGuysInTown** [comment]
Any progress on this? The library no long works for me after updating to swift 4

**Comment by pariz** [comment]
@ThoseGuysInTown same for me, compile it in swift 3.2 for now

**Comment by ZacharyKhan** [comment]
Seems #212 has been merged but I’m still running into issues of Swift 4 syntax with the pod, even after running `pod update`

**Comment by JunaidVizz** [comment]
not working in swift 4 :(

**Comment by ZacharyKhan** [comment]
@JunaidVizz I’m running the newest version (1.6.0) on Swift 4 without issues. Have you run `pod update`?

If so, what exactly is the error?

**Comment by JunaidVizz** [comment]
yes i did run pod update command.. it gives 15 syntax errors including
@IBinspectable and string.characters etc

**Comment by JunaidVizz** [comment]
now i did it my self. :) no need to use pod now..

**Comment by ZacharyKhan** [comment]
The syntax error you're seeing is a deprecation warning letting you know that particular function or property will be deprecated in an upcoming release. 

Are there any issues that **_keeping you from successfully compiling your project_**?

**Comment by heiyeliuying** [comment]
not working in swift 4

**Comment by maziyarpanahi** [comment]
Version 0.8.1 is now available on CocoaPods:
https://cocoapods.org/pods/ActiveLabel
