### ISSUE TITLE
ActiveLabel removes attributes in my attributed string

### ISSUE THREAD

**Issue by andreaslindahl** [optonaut/ActiveLabel.swift#219]
I have an attributed string with a lot of attributes. The string might also contain URL:s so I'm using ActiveLabel to highlight them and make them clickable. However, ActiveLabel removes or alters the existing attributes in my attributed string, which causes a lot of formatting issues. I've tracked it down to the updateTextStorage() method in ActiveLabel.swift, line #279:

```
 let newString = parseTextAndExtractActiveElements(mutAttrString)
 mutAttrString.mutableString.setString(newString)
```
It seems this removes the existing attributes.

Also, a couple of lines further down it sets the label's text, which also will remove any attributes:

`text = mutAttrString.string`

Is there any way to avoid this?

**Comment by chriszelazo** [comment]
I am also curious if there's an update here

**Comment by Asuard** [comment]
I have the same issue. 
What is the purpose of setting the text with the line `text = mutAttrString.string`  ? 
It is seems to be working well without this line.

**Comment by omerCoosto** [comment]
Any news?

**Comment by MaciejRz** [comment]
Well, it did hit me also. On iOS 11 is seems to preserve attributes in some way but on iOS 10 they get lost. As @Asuard noticed is seems to work on both OSes w/o these lines but is it completely irrelevant or can have some impact later on?

**Comment by andreaslindahl** [comment]
Will this be fixed anytime soon?

**Comment by maziyarpanahi** [comment]
is there any pull request for this issue?

**Comment by MartinMetselaar** [comment]
The following hack/workaround fixed the bug for me since I was only using one font.
```
let attributes: [NSAttributedString.Key: Any] = [
   .font: .font: UIFont.systemFont(ofSize: 12)
]
activeLabel.attributedText = NSMutableAttributedString(string: "Some nice text", attributes: attributes)
activeLabel.font = attributes[.font] as? UIFont // Fix for iOS 10
```
