### ISSUE TITLE
Error in Xcode 6.4

### ISSUE THREAD

**Issue by 13hika77** [optonaut/ActiveLabel.swift#22]
I use cocoapods to install this library but it shows errors everywhere.. can you tell me how to fix those errors? or is it can't be used in Xcode 6.4 ? thank you..
![screen shot 2015-12-02 at 12 52 15 pm](https://cloud.githubusercontent.com/assets/16112454/11523292/904da630-98f3-11e5-8860-2e215fd32040.png)

**Comment by schickling** [comment]
I've just tested the framework using XCode 7 and newer. I'm sorry.

**Comment by 13hika77** [comment]
So I can't use it, am I right?
