### ISSUE TITLE
Not clickable in  table view cell :(

### ISSUE THREAD

**Issue by alkincakiralar1996** [optonaut/ActiveLabel.swift#221]
```
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "commonCommentCell", for: indexPath) as! CommonCommentTableViewCell
        cell.getData(userPhotoUrl: self.commentList[indexPath.section].userThumbnailUrl!, userName: self.commentList[indexPath.section].userName!, message: self.commentList[indexPath.section].content!, date: self.commentList[indexPath.section].crtm!)
        cell.contentView.backgroundColor = UIColor.white
        cell.layer.cornerRadius = 5.0
        cell.layoutMargins.top = 15
        /*cell.optionsButton.accessibilityHint = String(describing: self.commentList[indexPath.section].id!)
        cell.optionsButton.accessibilityLabel = String(describing: self.commentList[indexPath.section].isOwner!)
        cell.optionsButton.accessibilityValue = "\(indexPath.section)"
        cell.optionsButton.isUserInteractionEnabled = true
        let optionButtonTapGesture : UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(openOptions(_:)))
        cell.optionsButton.addGestureRecognizer(optionButtonTapGesture)
        */
        //cell.selectionStyle = UITableViewCellSelectionStyle.none
        
        cell.messageLabel.enabledTypes = [.mention, .hashtag]
        cell.messageLabel.hashtagColor = UIColor(r: 78, g: 194, b: 205)
        cell.messageLabel.mentionColor = UIColor(r: 78, g: 194, b: 205)
        
        cell.messageLabel.handleMentionTap { (str) in
            print("NOT WORKING")
        }
        
        cell.messageLabel.handleURLTap { (str) in
            print("NOT WORKING")
        }
        
        return cell
    }
```
its not working do you know why it is happening ?

**Comment by jeffcaljr** [comment]
Having the same issue. Were you able to resolve this?

**Comment by maziyarpanahi** [comment]
I have mine in UITableViewCell and CollectionViewCell and I can tell you it is very much selectable. Can you please follow the basic example in a new UITableView see if it works? Also, the version of the ActiveLabel and your Swift may help as well.

**Comment by Mahan3340** [comment]
@jeffcaljr  @alkincakiralar1996 @maziyarpanahi  did you find any solution ?

**Comment by maziyarpanahi** [comment]
@jeffcaljr @alkincakiralar1996 @Mahan3340 
OK, I think I didn't get the question correctly. Is the TableViewCell not clickable or the Hashtags/URL/UserName are not clickable inside the TableViewCell?

**Comment by jeffcaljr** [comment]
No resolution thus far.

The TableViewCell itself is clickable; the tags/urls/usernames don’t respond to tap gestures. Long-pressing the links for almost exactly 3 seconds triggers their actions though.

**Comment by Mahan3340** [comment]
@maziyarpanahi @jeffcaljr  I had a gesture recognizer for dismissing keyboard on tap I managed to do it in another way so the click is fine for me now (doesn't take long time to be clicked , just like normal) and doesn't conflict with context menu long press , but Lagging still exists for non English text as I opened an issues for it .

**Comment by maziyarpanahi** [comment]
@jeffcaljr we do have issues open when the Cell itself is not selectable, but I don't think the tags/mentions/URLs not be clickable or taking long for action is related to UITableView.
I do have UITableView and UICollectionView which have ActiveLabel without any issue for selecting hashtags or URLs. 
Is there any customize gesture in the cell? Is it possible to just have a simple UITableView and check this separately to be sure nothing else is interfering?

**Comment by maziyarpanahi** [comment]
@Mahan3340 I follow up in your issue for other users in the future.

**Comment by Mahan3340** [comment]
@pawanline I'm not currently using this Lib but back then as I said above , there was an gesture recognizer that was catching all the touches to dismiss Keyboard when user taps around , by removing it or modifying it so that it wont consume the touch , the click was working again . you might have something like that in your table , test is with a simple table with cells containing just labels and see if it works for you or not .

**Comment by pawanline** [comment]
@Mahan3340 thank man finally I solved my issue.I have done the same mistake as you.

**Comment by maziyarpanahi** [comment]
I am happy this issue has been resolved. Thanks @Mahan3340  for instruction and thanks @pawanline for confirming the fix.

**Comment by Patrick-Remy** [comment]
In my case the solution was to add this to the custom cell class, so that the touch events are propagated down to the label:

```swift
// MARK: - Pass touches events to ActiveLabel, so that tap handlers work

override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
    self.contentLabel.touchesBegan(touches, with: event)
    super.touchesBegan(touches, with: event)
}

override func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?) {
    self.contentLabel.touchesMoved(touches, with: event)
    super.touchesMoved(touches, with: event)
}

override func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?) {
    self.contentLabel.touchesEnded(touches, with: event)
    super.touchesEnded(touches, with: event)
}

override func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {
    self.contentLabel.touchesCancelled(touches, with: event)
    super.touchesCancelled(touches, with: event)
}
```

and use a custom form, to prevent endless delegate callings for those methods: https://github.com/Patrick-Remy/ActiveLabel.swift/tree/bugfix/endless-touches-events
