### ISSUE TITLE
updated to 0.8.0

### ISSUE THREAD

**Issue by piglikeYoung** [optonaut/ActiveLabel.swift#223]
I found that the library has been updated to 0.8.0, Swift 4 ,but cocoapods still is 0.7.1

**Comment by pakamob** [comment]
Same problem.
Can your do something please??

**Comment by maziyarpanahi** [comment]
For the moment you can do as follow:

`pod 'ActiveLabel', :git => 'https://github.com/optonaut/ActiveLabel.swift.git', :tag => '0.8.0'`

**Comment by vc7** [comment]
just a remind, the version in the podspec from tag `0.8.0` is still `0.7.1`
> s.version = '0.7.1'

**Comment by piv199** [comment]
@Optonaut

**Comment by james-ff** [comment]
Would be great to not have to use this specific tag anymore, any update? Surely this fix won't take long?

**Comment by ejoebstl** [comment]
@james-ff  
I think the maintainers of this project are inactive. I have no clue about pods, so I would rather not touch anything here. However, I can give you, if you're willing to resolve this issue?

**Comment by maziyarpanahi** [comment]
Hi @james-ff 
I think they are just very busy based on their git activities. I thank them nonetheless since they are contributing to open-source community.

I am guessing you are talking about write access to the repo? This won't help. Someone who has access to CocoaPods can only add contributors to the CocoaPods so other can push new versions by using Trunk:
https://guides.cocoapods.org/making/getting-setup-with-trunk.html#adding-other-people-as-contributors
You can add me if you have this access and I will release the new version on CocoaPods with pleasure.

**Comment by james-ff** [comment]
Sounds like @ejoebstl could give @maziyarpanahi access to update the podspec / cocoapod etc?

(Also, thank you contributors for making libraries such as this accessible and open source!)

**Comment by ejoebstl** [comment]
@maziyarpanahi I will reach out to @schickling, who is afaik the maintainer on CocoaPods.

**Comment by maziyarpanahi** [comment]
@ejoebstl sounds great! In fact the `ActiveLabel.podspec` is already set to the right version, it's just need a little bit of push :)
Thanks Emanuel!

**Comment by maziyarpanahi** [comment]
@schickling @ejoebstl 
I had to bump the version to 0.8.1 since the 0.8.0 had a wrong version for podspec and it's not possible to commit in git tags.
Now all I need is to be added to cocoapod (from the link I posted here) and I will push the latest code as 0.8.1 :)

Many thanks

**Comment by maziyarpanahi** [comment]
I can see @efremidze has access to ActiveLabel pod.

**Comment by maziyarpanahi** [comment]
@efremidze thanks mate!
Cocoapods has been updated to 0.8.1
https://cocoapods.org/pods/ActiveLabel

**Comment by efremidze** [comment]
https://github.com/optonaut/ActiveLabel.swift/pull/231

**Comment by ejoebstl** [comment]
@efremidze Thanks so much!
