### ISSUE TITLE
Custom ActiveType works only if you set the text to UILabel after setting enabledTypes

### ISSUE THREAD

**Issue by ov1d1u** [optonaut/ActiveLabel.swift#224]
This will not work:

```
label.text = "This is a post with #hashtags and a @userhandle."
let customType = ActiveType.custom(pattern: "\\swith\\b") //Regex that looks for "with"
label.enabledTypes = [.mention, .hashtag, .url, customType]
label.customColor[customType] = UIColor.purple

```
but this will:

```
let customType = ActiveType.custom(pattern: "\\swith\\b") //Regex that looks for "with"
label.enabledTypes = [.mention, .hashtag, .url, customType]
label.text = "This is a post with #hashtags and a @userhandle."
label.customColor[customType] = UIColor.purple
```
I don't know if this is the intended behaviour but, if it is, it would be great if you update the documentation on the README.md to reflect this, it took me a while to find that a custom `ActiveType` is not applied until you set the label's text, so maybe this will help others to figure this out quicker.

**Comment by AssyriaGameStudio** [comment]
You sir are a legend... Been banging my head against a wall the last 30 mins trying to figure this out!

**Comment by maziyarpanahi** [comment]
I am going to update the README.md, thanks @ov1d1u for testing this and @AssyriaGameStudio for confirming this is still the case in the latest version.

**Comment by maziyarpanahi** [comment]
done!

**Comment by dihardjajames** [comment]
this guy's the real MVP, been spinning my head until I find this thread
