### ISSUE TITLE
Mention pattern does not give an option for matching dots

### ISSUE THREAD

**Issue by demonar** [optonaut/ActiveLabel.swift#228]
`static let mentionPattern = "(?:^|\\s|$|[.])@[\\p{L}0-9_]*"`
the pattern only accepts mentions without dots and some social networks are accepting dots in the user handle, if you look at the mentions regex on https://github.com/regexhq/mentions-regex/blob/master/index.js you'll see that is more accurate and closer to the one implemented by twitter, with an option to accept the dot, here's the url for the objc version of the twitter regex: https://github.com/twitter/twitter-text/blob/master/objc/lib/TwitterText.m

**Comment by demonar** [comment]
i'll try to modify the regex matching on my fork and create a PR, but if you reach to the solution before please let me know 😄

**Comment by Jitenderios** [comment]
have you found any solution to this?

Thanks,
Jitender

**Comment by demonar** [comment]
@Jitenderios yes, i found it, i need to create a PR and propose it
