### ISSUE TITLE
Master branch with Swift 4 doesn't support Pod integration in ObjC project

### ISSUE THREAD

**Issue by petrovi4** [optonaut/ActiveLabel.swift#229]
ActiveLabel havn't `handle*Tap` methods after pod integration in objective c project.
Last master commit #0cf36d33138c0c3795ea08d632e6f26acbfb6551
Swift 4.0

**Comment by maziyarpanahi** [comment]
Hi @petrovi4 
Can you try `0.8.1` and see if it's still the same problem. Just wanted to be sure you have the latest release.
tnx

**Comment by dimovskidamjan** [comment]
I still cannot build an Objective-C project which uses ActiveLabel. The error says that the handleXXXTap methods have no visible interface. I'm using Swift 4 for the project and the pod.
