### ISSUE TITLE
URLs without "http://" and "https://" are not detected

### ISSUE THREAD

**Issue by annjawn** [optonaut/ActiveLabel.swift#235]
If a URL is shows up without "http://" or "https://" in the text label then it is not detected. For example this URL ->  es.pn/2n8CW3w  is not detected but it is a valid URL.

**Comment by arielelkin** [comment]
Any updates on this ?

**Comment by annjawn** [comment]
Nope. I ended up writing my own UILabel subclass. NSDataDetector, which is used to detect links, currently doesn’t support short urls or (e.g: bitly urls) or urls without an http:// or https:// prefix, which is the problem. But I guess you can define a custom type using regular expressions to make it work.

**Comment by hiren1995** [comment]
let urlString = $0.absoluteString
//get the url string

var openURL = URL()

if urlString.hasPrefix("http://")
  {
                    openURL = URL(string: urlString)!
  }
else if urlString.hasPrefix("https://")
  {
                    openURL = URL(string: urlString)!
  }
                else
   {
                    openURL = URL(string: "https://" + urlString)!
   }
               
// I tried to edit regular expression in regex file of library but didn't worked so found this way..!

**Comment by annjawn** [comment]
@hiren1995 I did this too but there are many bit.ly short URLs that is just too difficult to parse and detect. I finally ended up using [twitter-text](https://github.com/twitter/twitter-text) which does pretty accurate hashtag, at mentions, cash tags, URLs (short or long any variation) detection and merge the gesture and tap logic from this library and ended up with a pretty accurate text detection lib.

**Comment by rahulvyas** [comment]
> @hiren1995 I did this too but there are many bit.ly short URLs that is just too difficult to parse and detect. I finally ended up using [twitter-text](https://github.com/twitter/twitter-text) which does pretty accurate hashtag, at mentions, cash tags, URLs (short or long any variation) detection and merge the gesture and tap logic from this library and ended up with a pretty accurate text detection lib.
> 
> FYI, twitter-text library uses the Verisign IDN library to detect international domains in URL including short urls, so it's pretty accurate as compared to the `NSDataDetector`.

Can you provide some sample code with Read More/Show Less and if you haven't implemented these then with @mention and Hash Tag with Hyperlink tap code.
