### ISSUE TITLE
adjustsFontSizeToFitWidth doesn't work 

### ISSUE THREAD

**Issue by alexanderkhitev** [optonaut/ActiveLabel.swift#237]
Hello! I use ActiveLabel (0.8.1) and `adjustsFontSizeToFitWidth` doesn't work

**Comment by AllanAraujo** [comment]
same issue with minimumScaleFactor

**Comment by revolter** [comment]
I don't get it. This big and popular library doesn't support this very common case, yet [this simple implementation](https://stackoverflow.com/q/26675439/865175) works perfectly 😕
