### ISSUE TITLE
Vertical align not correct after setting textAligment

### ISSUE THREAD

**Issue by poolqf** [optonaut/ActiveLabel.swift#24]
Hi,

I am using ActiveLabel in my app, and there's a case where I need the text to be horizontal and vertical aligned. But setting the `textAlignment ` property does not change anything.

I added a line on the `addLineBreak(attrString:)` method expecting it to center the text as expected, but the result is the following:

<img width="380" alt="screen shot 2015-12-05 at 19 32 29" src="https://cloud.githubusercontent.com/assets/7887319/11609444/0e9871d8-9b87-11e5-80ef-ff10076534f2.png">

Correct center alignment, but incorrect vertical one.

```swift
/// add line break mode
    private func addLineBreak(attrString: NSAttributedString) -> NSMutableAttributedString {
        let mutAttrString = NSMutableAttributedString(attributedString: attrString)
        
        var range = NSRange(location: 0, length: 0)
        var attributes = mutAttrString.attributesAtIndex(0, effectiveRange: &range)
        
        let paragraphStyle = attributes[NSParagraphStyleAttributeName] as? NSMutableParagraphStyle ?? NSMutableParagraphStyle()
        paragraphStyle.lineBreakMode = NSLineBreakMode.ByWordWrapping
        paragraphStyle.alignment = textAlignment //ADDED THIS
        if let lineSpacing = lineSpacing {
            paragraphStyle.lineSpacing = CGFloat(lineSpacing)
        }
        
        attributes[NSParagraphStyleAttributeName] = paragraphStyle
        mutAttrString.setAttributes(attributes, range: range)
        
        return mutAttrString
    }
```

A solution to accomplish the center alignment would be to add a `didSet` on it, as on the other variables.
As for the vertical alignment, I tried a lot of things to accomplish it, but without luck, so I have no clues...

PS. I have an extension of ActiveLabel that uses a delegate instead of having to set block for each Label you create to handle user touches. Do you want me to create a PR with it?

**Comment by schickling** [comment]
Hi @poolqf. Thanks for your issue. Please go ahead and open a PR :+1:

**Comment by xScylez** [comment]
Did you manage to fix this issue about the alignment?

**Comment by poolqf** [comment]
Nope @xScylez , the only thing I fixed was horizontal alignment, but not the vertical one. 

But a workaround could be to use the horizontal alignment fix, and then make the UILabel height fit to size, and then manually center the label inside the view you want

**Comment by xScylez** [comment]
@poolqf Could you post an example code for your workaround please? I don't fully understand what you mean.

**Comment by poolqf** [comment]
Taking #31 , that is fixing the horizontal alignment, the workaround for fixing de vertical alignment, in a really verbose way, could be something like this:

```swift
    let containerView = UIView()
    containerView.frame = CGRect(x: 0, y: 0, width: 150, height: 50)
    let label = ActiveLabel()
    label.text = "My Text"
    label.textAlignment = .Center
    label.sizeToFit()
    let containerHeight = containerView.frame.height
    label.frame = CGRect(x: 0, y: containerHeight/2 - label.frame.height/2, width: containerView.frame.width, height: label.frame.height)
    containerView.addSubview(label)
```

**Comment by xScylez** [comment]
@poolqf What about if the label is already declared as a ActiveLabel in Storyboard? I can access the label using the command `imageCell.imageText`.

**Comment by poolqf** [comment]
@xScylez using Storyboards it should be even easier if you play with the correct constraints
