### ISSUE TITLE
How to fix the url that contain Chinese?

### ISSUE THREAD

**Issue by Bruce9487** [optonaut/ActiveLabel.swift#245]
I run the demo and change the url string that contain Chinese.
How to fix it? 
Thanks.
URL String: https://zh.wikipedia.org/zh-cn/斯蒂芬·科里

![simulator screen shot - iphone 8 - 2018-03-12 at 10 33 42](https://user-images.githubusercontent.com/19691907/37263781-aae48826-25e4-11e8-9a91-134cddf82829.png)

**Comment by Bruce9487** [comment]
Any idea to me?

**Comment by qhu91it** [comment]
You can use customType to set your regex, using \p{han} or \p{L}, \w to detect, for a specific character like middle dot (‧) I don't know pattern for it, maybe need to add manually.
