### ISSUE TITLE
is it possible to add read more and show less feature(like in instagram and other social app "..Read more") with this Active label library without writing own logic ?

### ISSUE THREAD

**Issue by sarathdev** [optonaut/ActiveLabel.swift#246]

**Comment by maziyarpanahi** [comment]
I am afraid the only thing comes to my mind is playing with the height/truncate options in UILable programmatically where you have your UILable as a summary with default height and the famous ... at the end of the text that suggests the content is bigger. Then a button that resizes the UILable to fit the entire content inside the UILable.

**Comment by sarathdev** [comment]
we can keep a button below the UILabel but still, can we make it the label to 4 rows when it is truncated and other cases the entire comment. Setting height will look weird on differently sized screens

**Comment by maziyarpanahi** [comment]
I think you can change the row number dynamically and with the auto-layout, it will fit the label perfectly in your cell/view.

**Comment by Ankooo12** [comment]
@maziyarpanahi  @sarathdev @fluidsonic @tony-pizza @joshdholtz 

can you share the code for this? It's very urgent and I am making app in swiftui so Please make like that.

Thank you
