### ISSUE TITLE
CocoaPods version

### ISSUE THREAD

**Issue by SeRG1k17** [optonaut/ActiveLabel.swift#248]
//Podfile
pod 'ActiveLabel'

//Podfile.lock
PODS:
  - ActiveLabel (0.8.1)
```swift
guard let maxLenght = maximumLenght, word.characters.count > maxLenght else {
//...
```
And of course it causes warning: 'characters' is deprecated: Please use String or Substring directly

If set the value as:
//Podfile
pod 'ActiveLabel', :git => 'https://github.com/optonaut/ActiveLabel.swift.git',  :branch => 'master'

```swift
guard let maxLenght = maximumLenght, word.count > maxLenght else {
//...
```
All right.

**Comment by maziyarpanahi** [comment]
Hi, the warning has been resolved in Master branch as you saw already and will be accessible with the next release on CocoaPods. 
However, the warning won't make an issue with production as I have 2 apps with 0.8.1 already on App Store, but you are welcome to try the Master for all the recent changes.

**Comment by SeRG1k17** [comment]
@maziyarpanahi 
I know that this will not interfere with the AppStore. Just the customer requires 0 warnings in the project. I think it's better to use a direct link to the master. 
Thanks, I'm waiting for a new version :)

**Comment by maziyarpanahi** [comment]
That makes sense :) I see if there are other changes in Master so I can release it on CocoaPods.
