### ISSUE TITLE
If tag words have space, it'll fail to tag.

### ISSUE THREAD

**Issue by Bruce9487** [optonaut/ActiveLabel.swift#249]
<img width="203" alt="2018-03-27 2 43 35" src="https://user-images.githubusercontent.com/19691907/37950966-454f5960-31cd-11e8-9c9e-78ad339317db.png">

       //regexArray = ["@[A-Za-z0-9]{4}\\s[A-Za-z0-9]{3}\\s", "@[A-Za-z0-9]{5}\\s[A-Za-z0-9]{1}\\s"]
         
        myTextLabel.customize { (label) in
             
            label.text = string
            
           **//Two of these Tap function will conflict.**
             regexArray.forEach { (regexStr) in
                
                let customType = ActiveType.custom(pattern: regexStr)
                label.enabledTypes.append(customType)
                label.customColor[customType] = UIColor.blue
               
               label.handleCustomTap(for: customType, handler: { (customString) in
               print("-->\(customString)") // tap "004" print "test 004" & tap "k" print "kevin"
            }) 

           }
           
            label.handleMentionTap({ (mentionString) in
                print("-->\(mentionString)")   // tap "test" print "test" & tap "kevin" print "kevin" & tap "ccc" print "ccc"
                
            })
                        
        }

I want to tap "test 004" in any words also print "test 004".
The same as "Kevin k".
How to fix it?

**Comment by pvcary** [comment]
I have the same issue :(... My example below:

```
//I'm using the white space "\u{00a0}" to separate my first name and last name...

let edited = name.replacingOccurrences(of: " ", with: "\u{00a0}")
let mention = "@" + edited

//I'm printing out my first name (space) last name, but ActiveLabel only recognizes my last name.

```
Similar to Bruce, would love to get other ideas for achieving highlighted mentions with a white space.

Thanks!!

**Comment by pvcary** [comment]
Hey @Bruce9487 @polqf ,

From trying to use the ActiveLabel mention with a white space in between a first and last name, I recently updated the mentionPatter from the RegrexParser like below:

> static let mentionPattern = "(?:^|\\s|$|[.])@[\\p{L}0-9_**\\s**]*"

This appears to be working for me but it almost seems too simple to be true. Might be worth taking further look, but this might help with a few issues in the repository.

Cheers,
Patrick

**Comment by FaranMushtaq** [comment]
In regex parser replace the given code:
static let mentionPattern = "(?:^|\\s|$|[.])@[\\p{L}0-9_]*" 
with 
static let mentionPattern = "(?:^|\\s|$|[.])@[\\p{L}0-9_\u{00a0}]*" 

let name = "Alex James"
let edited = name.replacingOccurrences(of: " ", with: "\u{00a0}")
let mention = "@" + edited

**Comment by maziyarpanahi** [comment]
This is a custom pattern based on your use case.
