### ISSUE TITLE
not working for label inside tableview cell

### ISSUE THREAD

**Issue by JainamOpenxcell** [optonaut/ActiveLabel.swift#250]
i have active label in my tableview cell and i want able to get click on the text for all cell .

i am using active label custom type .

**Comment by KheangSenghort** [comment]
me too

**Comment by Spyspyspy** [comment]
me too

**Comment by LouisBorlee** [comment]
Hi!

Same here, any update? I've been struggling to find any solution at all on the matter.

**Comment by maziyarpanahi** [comment]
Guys, is the `userInteractionEnabled` set to `true`?  Have you tried simply adding `UITapGestureRecognizer` to the UILable and have your selector to do what you want to do? Like segue or something.

**Comment by maziyarpanahi** [comment]
This already being resolved here and is not related to ActiveLabel. 
Feel free to re-open it if you think it is directly related to this library.
