### ISSUE TITLE
Poor performance inside UITableViewCell

### ISSUE THREAD

**Issue by daurenm** [optonaut/ActiveLabel.swift#251]
Hi there,

Seems like the pod does too many things in the main thread, blocking it.

<img width="842" alt="screen shot 2018-03-31 at 2 22 12 pm" src="https://user-images.githubusercontent.com/13380740/38161345-301b3332-34ef-11e8-96c6-e4e425c73fb9.png">

Here is code:

    // cell for row uses this method to update text
    func updateText(_ text: String) {
        let userName = "daurenmuratov"
        let comment = "@\(userName):"
            + (" \(text)")
        textView.text = comment
    }
    
    // initializing ActiveLabel
    lazy var textView: ActiveLabel = {
        let al = ActiveLabel()
        al.customize({ (label) in
            label.numberOfLines = 0
        })
        return al
    }()

Here is the same text: 

`Some dummy #long long text here www.aksdha.com sjhda shd #jshd jashd jahsd @jashd jashd www.jashd.com jahsdjahs djahsjd ahsjd ahjs dahjs dajshd jahsd jahs jdah jdsahj @das`

Is there anything can be done with that? :)

**Comment by maziyarpanahi** [comment]
Hi @daurenm,

May I know a bit more about your spec? 
iOS version, Swift version, and device you are trying it (simulator or real). 
Also, by poor performance, you mean laggy when you are scrolling or just concern that the majority of CPU goes to draw ActiveLabel inside the cell?

As a test, I built this app and tested with iPhone 6s Plus (not really recent device). You can give it a try, you know where the ActiveLabel is when you see them. (Keep in mind the loading remove images and other objects inside the cells).
https://itunes.apple.com/ao/app/politoscope/id1312641780

PS: I remove the link after you tested to avoid self advertising even though the whole thing is french so probably useless outside France :)

**Comment by daurenm** [comment]
hi @maziyarpanahi,

This app is laggy. I don't know for sure if it's due to activeLabel itself, or something totally different :(

**Comment by maziyarpanahi** [comment]
Hi @daurenm,
By `this app` you mean the one in the link or your own app? Cause I checked mine for performance and it is not laggy.
What is your test device? And can you provide the code inside `cellForRowAt` pr other delegations if you change any heights?
