### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by akshatsd2** [optonaut/ActiveLabel.swift#252]
Hi,

My project is running on swift 3 as ActiveLabel version has been upgraded to swift 4 so i used to set it's version on swift 4 but now as i upgraded to new xcode 9.3 it has started giving me error. 
error: fatal error encountered while reading from module 'ActiveLabel'; please file a bug report with your project and the crash log
<unknown>:0: note: compiling as Swift 3.3, with 'ActiveLabel' built as Swift 4.1 (this is supported but may expose additional compiler issues)

**Comment by MuthuVenkateshM** [comment]
@akshatsd2 Facing the same issue. Any suggestions?

**Comment by anatoliyv** [comment]
@akshatsd2 @MuthuVenkateshM Did you solved it?

**Comment by MuthuVenkateshM** [comment]
yes, I solved it by configuring swift build version for the pod to 4.1 during install itself. Adding the code below,
`post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'ActiveLabel' 
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.1'
            end
        end
    end
end`

**Comment by anatoliyv** [comment]
@MuthuVenkateshM, nice, thank you!

**Comment by Aft3rmathpwnz** [comment]
Have the same issue, unfortunately it didn’t help me, still get abort error: 6
