### ISSUE TITLE
Not working properly tap event

### ISSUE THREAD

**Issue by albetoetecnia** [optonaut/ActiveLabel.swift#255]
Hi! I'm having problems to get tap event on customType, neither working mentions, hashtags...
This is my code:

       ```
        let text = "remember_pwd".localized
        let customType = ActiveType.custom(pattern: "\\s" + "click_here".localized + "\\b")
        label_password_remember.numberOfLines = 0
        label_password_remember.isUserInteractionEnabled  = true
        label_password_remember.isMultipleTouchEnabled  = true
        label_password_remember.enabledTypes = [.mention, .hashtag, .url, customType]
        label_password_remember.textColor = .white
        label_password_remember.text = text
        label_password_remember.customColor[customType] = UIColor.white
        label_password_remember.customSelectedColor[customType] = Common.UIColorFromRGB(Common.Color.APP_COLOR_ACCENT)
        
        label_password_remember.handleCustomTap(for: customType) { (element) in
            print("Custom type tapped: \(element)")
            self.performSegue(withIdentifier: "action_remember_password", sender: nil)
        }
```
Only enter on handleCustomTap a few time (random). The label is created in storyboard. Swift 4.
I hope you can reproduce, it's very easy I think.

Regards

**Comment by fpena** [comment]
I think this happens with multiline labels. Having same issue here.

**Comment by rakkang** [comment]
Env:
- Xcode 10.1
- Swift 4
- iOS 12.1

Use source integration instead of cocoapod,  modify `func onTouch(_ touch: UITouch)`：

```swift
...

case .ended, .cancelled:
    guard let selectedElement = selectedElement else { return avoidSuperCall }
    
    ...
   
// case .cancelled:
//  updateAttributesWhenSelected(false)
//  selectedElement = nil

...

```

It's working！

**Comment by vani2** [comment]
If someone want you can use [my fork ](https://github.com/RedMadRobot/ActiveLabel.swift).
```ruby 
pod 'ActiveLabel' , :git => 'git@github.com:RedMadRobot/ActiveLabel.swift.git', :branch => 'master'
```

**Comment by maziyarpanahi** [comment]
Hi!
If this is a real issue that needs to be fixed, please feel free to create a pull request. I'll merge it after a test for the next release.

Thanks everyone.

**Comment by adiahuja07** [comment]
Any updates. I am also facing the same issue. If the user taps for a little longer then it gets registered otherwise it is skipped.

**Comment by vani2** [comment]
@adiahuja07 did you tried my fork?
