### ISSUE TITLE
Some of characters were cutted

### ISSUE THREAD

**Issue by mrhaxic** [optonaut/ActiveLabel.swift#258]
ActiveLabel working properly if the text in English, I tried to use another language such as Arabic but some of the characters were been cutted as below

<img width="388" alt="screen shot 2018-05-28 at 9 38 50 pm" src="https://user-images.githubusercontent.com/11592785/40626236-ead1182e-62bf-11e8-8347-b66c5d39a55c.png">

**Comment by maziyarpanahi** [comment]
This is probably for Right-to-Left languages, I have tried this library in French/English and it works as it's expected.
Is it the position of the @User that is wrong? Where is the data coming from? Usually, there are problems with combining Right to Left and Left to Right on almost all the current applications. I am guessing this is not related to the library if you can manage to position the mixed language in your text.

**Comment by mrhaxic** [comment]
Hello @maziyarpanahi, yes as you said it is contained within mixed languages and what do you mean by " manage to position the mixed language in your text "

Appreciated

**Comment by maziyarpanahi** [comment]
Hello @mrhaxic 
Sorry I didn't express what I meant smoothly. I meant, is it cutting letters if it's at the end or it happens even if it is in the middle. Also, is the position of the other language in the text is right and expected or is it changing?
However, can you debug your UI in XCode and see what is going on in there? Is it cutting entirely or overlying somehow. 
Another way to debug is to track this sentence and log it in the console. The moment you receive it before assigning it, after you assigning it, even the  `mention` event can show you what is in the full text.

**Comment by mrhaxic** [comment]
@maziyarpanahi Actually, while debugging the UI by Xcode, it seems that the library doesn't show the full text

**Comment by mrhaxic** [comment]
This is a good replacement, I tried and it is working properly and like a charm!

https://github.com/psharanda/Atributika
