### ISSUE TITLE
TableView Lagging with Very Long texts + Truncated 

### ISSUE THREAD

**Issue by Mahan3340** [optonaut/ActiveLabel.swift#262]
Hi , I've tested your lib in very long text and lags so bad while scrolling , Tableview has more than 15 item types and works just fine without a single lag when switching back to normal UILabel with more than 1000 items in the table , so its the lib problem I guess , any solution ? also I've to mention that even the label doesn't have any Hashtag,Link,Username but it lags anyway + half of the text isn't even shown and its just empty when using ActiveLabel with long texts which is again working well with UILabel .
** : this is happening in a RTL language (Persian)
tested on Simulator iOS 11 Swift 4 , iphone 6s iOS 11 , iphone 6s Plus iOS 11 , Xcode 9 latest version
lib version : 0.9.0

**Comment by maziyarpanahi** [comment]
This is an interesting find both on the length and performance being different in RTL languages. Is this app available for download?

Note 1. Even without any hashtags/URLs/mentions the library still does the regex lookup. So, unless you manually turn off those options (if you don't need them) it will be kind of the same.

Note 2. There are one too many variables in this problem. Loading 1000 items in the UITableView and long text in the UILable make it hard to diagnose. Is it possible to reduce the number of cells to something like 100? Also, have a number of lines set to make sure it won't go to wild as the text gets longer the library has more text to go through.

**Comment by Mahan3340** [comment]
@maziyarpanahi  its not available for download , in fact i realized that UILabel in UITableview is laggy anyway with long non english text even with plain Swift UILabel and being digging for months and couldn't find any solution to that

**Comment by maziyarpanahi** [comment]
It's a good catch @Mahan3340,
Do you think to make everything the same length and having a `read more` button/link at the end of the text will help? And of course, you should collapse the long text when user taps on another text to see more. This way you always have one long text in the UITableView.

**Comment by Mahan3340** [comment]
@maziyarpanahi  its a messaging app so its not like a good idea to have read more button , and also its not that lengthy its just 400 500 char text so its  few lines fully visible in a screen

**Comment by maziyarpanahi** [comment]
OK, then that is weird! 400-500 characters is not a very long text. Just to be absolutely sure, can you please add these text to an array of strings and load it from there. I want to be sure there is no network/update loop somewhere in the process. In fact, can you create a new UITableViewController and do it there, just be to sure there is nothing being called a few times every time there is a cell being visible.

**Comment by Mahan3340** [comment]
@maziyarpanahi yea its weird , actually I've tested this , created a new VC with a simple Table with cells containing just Label , the only thing that was being called repeatedly when cells became visible was to set the text ! at first I tested it with similar texts ( all cells the same ) and it was smooth no matter how lengthy they were , then I used different texts for each cell and the lag started :-/

**Comment by Mahan3340** [comment]
@maziyarpanahi I finally managed to solve this issues , the problem is that ios Default system fonts or any other fonts that are meant to support English (but can render other languages too, such as Persian) can't render other languages well , so what I had to do was to simply use a font that is meant to support Persian like "B Nazanin" , "IRANSans" , ... which they can render English too , in this way the lag is completely gone and scrolling is as smooth as it should be

**Comment by maziyarpanahi** [comment]
Wow! I would have never thought about rendering fonts with support for RTL languages in a million years! Great catch @Mahan3340 and cheers!
