### ISSUE TITLE
Not displaying properly if I add multiple image attachments

### ISSUE THREAD

**Issue by NervousTweek** [optonaut/ActiveLabel.swift#266]
When I add one image attachment to the attributedText property, it goes well. But when adding two or more attachments, only the first one is shown. And if I change ActiveLabel to UILable and leave the rest codes, all these attachments are shown.

**Comment by ThoseGuysInTown** [comment]
Haha I'm having trouble even getting one attachment to show up. How did you do it?

**Comment by NervousTweek** [comment]
For now, this function may be not implemented yet, so I use another library called [Atributika](https://github.com/psharanda/Atributika) and it works for me. You can download the demo to see how it works and if you still have problem attaching image, you might see [this](https://github.com/psharanda/Atributika/issues/39).
