### ISSUE TITLE
Custom start word in sentence not changing color

### ISSUE THREAD

**Issue by umeshiscreative** [optonaut/ActiveLabel.swift#269]
```
let customType = ActiveType.custom(pattern: "\\sAre\\b")
label.enabledTypes.append(customType)

label.text = "are They have a post with #multiple"

label.customize { label in
   label.customColor[customType] = UIColor.purple
}
```

'are' key word not change its color..

**Comment by benjaminledet** [comment]
Same for me

```
let customType = ActiveType.custom(pattern: "\\stest\\b")
label.enabledTypes.append(customType)

label.text = "test doesn't work"
label.text = " test work"
```

**Comment by sluitel** [comment]
+1 I am getting the same issue

**Comment by gershengoren** [comment]
`\\s` means a whitespace

**Comment by Jitenderios** [comment]
@gershengoren @sluitel @benjaminledet I am facing the same issue. Did you found a way round to this issue. 
Thanks

**Comment by khush004** [comment]
@gershengoren @sluitel @benjaminledet @Jitenderios  I am also facing the same issue, Did you found any solution?

**Comment by khush004** [comment]
Hello All I found the solution Please try this : - **ActiveType.custom(pattern: "(?:^|\\s|$)\(Name)\\b")**

**Comment by hirenvolansys** [comment]
I am also facing the same issue.  Please let me know if anyone found the solution. @khush004, didn't work this.
