### ISSUE TITLE
One letter usernames not detected

### ISSUE THREAD

**Issue by williamsthing** [optonaut/ActiveLabel.swift#271]
I have a user who signed up to my app with a one letter username. Wherever their username (@l) is found, it does not get detected by ActiveLabel. Is there a configuration option for min username length? Thanks!

![image0](https://user-images.githubusercontent.com/8293444/44281283-33349400-a24f-11e8-885c-7a606fec8f93.png)

**Comment by maziyarpanahi** [comment]
Not sure, but I saw minLength somewhere is 2. Can you please test with 2 characters to see if it works?
As a side note, it is best practice to have minLength for the username on your backend plus some reserved names :)
