### ISSUE TITLE
New Line (\n) posted from Android is not showing in iOS as new line

### ISSUE THREAD

**Issue by sarathdev** [optonaut/ActiveLabel.swift#272]
New Line (\n) posted from Android is not showing in iOS as the new line. But when I post from iOS With enter key it is working fine

**Comment by maziyarpanahi** [comment]
I am assuming you have some sort of backend. Can you please debug the text to see what is the special character for the new line in both iOS and Andriod?

**Comment by sarathdev** [comment]
@maziyarpanahi  Sorry and thanks for the time and reply. It was not updating because of some conversion doing in the android side. We removed it and working fine for both OS
