### ISSUE TITLE
Compatible with XCode 10 and Swift 4.2

### ISSUE THREAD

**Issue by Maxwell6635** [optonaut/ActiveLabel.swift#274]
Compatible with XCode 10 and Swift 4.2
NSAttributedStringKey' has been renamed to 'NSAttributedString.Key
Replace 'NSAttributedStringKey' with 'NSAttributedString.Key

**Comment by maziyarpanahi** [comment]
Hi, I am going to review the pull requests and release a branch or 4.2 next week.

**Comment by tapannathvani** [comment]
Hello, Can i know when you are going to release a new version ?

**Comment by kachalovsky** [comment]
My super mega popular app crashed. Could you please update lib to swift 4 and xCode 10

**Comment by maziyarpanahi** [comment]
I am sorry this library is already Swift 4.0 and it is compatible with XCode 10. You just need to keep "compile with Swift 4.0" in your pod. Your entire project (codes and other pods) can be compiled by Swift 4.2 while ActiveLabel is still on 4.0 without any problem.
I just released a new version of my app with the same situation without any crash nor problem. Your crash must have some other reasons.
I do agree the version 4.2 is a must and as soon as I come back from my trip when I have my dev resources I will finish it, but you can do as I mentioned if it is mandatory to go with Swift 4.2.

**Comment by kachalovsky** [comment]
@maziyarpanahi thank you

**Comment by maziyarpanahi** [comment]
Hi guys,
Here is the release: https://github.com/optonaut/ActiveLabel.swift/releases/tag/1.0.1
