### ISSUE TITLE
iOS 12 default font bug

### ISSUE THREAD

**Issue by lvloh3n** [optonaut/ActiveLabel.swift#279]
Hey man
Thank you for your great pod

There is a new issue, if I use iOS 12 with default font the result will be like this picture
![simulator screen shot - iphone 7 - 2018-09-29 at 22 17 58](https://user-images.githubusercontent.com/4413654/46250023-c6144100-c43f-11e8-8130-275da291c1e9.png)

if I use older iOSs or any other font the result would be ok like this
![simulator screen shot - iphone 7 - 2018-09-29 at 22 18 20](https://user-images.githubusercontent.com/4413654/46250027-ce6c7c00-c43f-11e8-899c-3b329672f233.png)

Do you have an idea what the problem should be?

**Comment by maziyarpanahi** [comment]
Hi @lvloh3n,
This must be a font issue rather than the library. But we had this discussion about Right-To-Left languages and their performance here: https://github.com/optonaut/ActiveLabel.swift/issues/262#issuecomment-414679837
