### ISSUE TITLE
Other detected (phone, email...) are show in link

### ISSUE THREAD

**Issue by qhu91it** [optonaut/ActiveLabel.swift#281]
I have link exam: http://exam.com/data?email=exam@mail.com&phone=0123456789.
I want it to detect as a link and tap full on it, but sometimes it detects both email and phone in this.
How I can prevent it, thanks.

**Comment by maziyarpanahi** [comment]
If you are not using @ or # to detect user handlers or hashtags, how about disabling those from annotating the text?
