### ISSUE TITLE
CustomHandle does not work sometimes

### ISSUE THREAD

**Issue by rodriar** [optonaut/ActiveLabel.swift#285]
I have created a new custom tap in order to work with usernames that contain dots. This led to an issue where the handle only seems to be work sometimes depending on the build. I will build and run the app and the custom tap will work. Do it again and it wont work (non-custom handle still work). Did someone came up with the same problem?  And please feel free to ask for any info you might find relevant for this issue

**Comment by jalbano** [comment]
I'm noticing that my custom taps have a very small "hot spot". If I don't think about it and just quickly tap, it doesn't register - but if I take my time and aim a little higher than seems right, it works. I'd love a way to add some "padding" to the touch area.
