### ISSUE TITLE
Whitespace character before string also included in url

### ISSUE THREAD

**Issue by sakshiGoel26** [optonaut/ActiveLabel.swift#292]
I am using "ActiveType.custom(pattern: "\\stests\\b")" to make tests string a url, but it is including the whitespace character before the string in url line. Any help will be appreciated.

**Comment by julien-its** [comment]
Hi, did you find a solution ?

**Comment by julien-its** [comment]
Ok. I found.
I was searching contact us. with this "\\scontact us\\b"
White space at the biginning was taken. I use this instead and it's ok #"\bcontact us\b"#

**Comment by amd90** [comment]
@julien-its Using **\b** for both worked well. Thanks!
