### ISSUE TITLE
lineSpacing be cleaned When use attributedText

### ISSUE THREAD

**Issue by CivelXu** [optonaut/ActiveLabel.swift#296]
Hello, I encounter one issues,  lineSpacing be cleaned When I set attributedText in ActiveLabel;

**Comment by JulianSong** [comment]
I got that same issue. I created an ActiveLabel in a table view cell and set it's attributedText with lineSpacing attributed.  But the lineSpacing doesn't work. And all the other labels on this page which set with attributedText ,their lineSpacing attributeds have ignored.

**Comment by linW23** [comment]
u can use label.lineSpacing = xxx

**Comment by NikKovIos** [comment]
ActiveLabel works bad with attributed string. It set own lineSpacing in `fileprivate func addParagraphStyle(_ attrString: NSAttributedString) -> NSMutableAttributedString`

**Comment by gerchicov-bp** [comment]
WTF? It is not solved but is closed

**Comment by gerchicov-bp** [comment]
@CivelXu if it will help you - this control ignores some attributed string params by adding its own replacement properties. You can call "label.lineSpacing = ...".
Moreover this control not only ignores attributed string params - it tries to rewrite them. In other words I tried to create a variable with attributes string params and reuse but it became broken not only in `ActiveLabel` but in `UILabel` too.

**Comment by NikKovIos** [comment]
@gerchicov-bp open a new issue with mark to that issue
