### ISSUE TITLE
Events and scroll conflict

### ISSUE THREAD

**Issue by weiFans** [optonaut/ActiveLabel.swift#3]
Events and scroll conflict
I came to ask questions of, UILabel added to the UITableViewCell, slide UILabel not scroll.
Know where the problems userInteractionEnabled = true, how do you solve it？

**Comment by schickling** [comment]
Could you provide a concrete code example?

**Comment by weiFans** [comment]
ActiveLabel added to the UITableViewCell
ActiveLabel slide up and down does not work
https://youtu.be/P0SD4-Uou-E

**Comment by schickling** [comment]
Ah, now I see what you mean! I'll try to fix that asap.

**Comment by schickling** [comment]
This should be solved in `0.2.1`. Thanks for reporting this problem. :+1: 

PS: Don't mind the broken build badge. That's a problem related to `xctool`

**Comment by weiFans** [comment]
Thank you very much to solve the problem, ActiveLabel.swift Bang Bang da!
Plus the best long press effect, hee hee!
