### ISSUE TITLE
UILabel vertical alignment

### ISSUE THREAD

**Issue by xScylez** [optonaut/ActiveLabel.swift#30]
UILabel as a Active Label does not center as a normal UILabel:

Image in Storyboard: http://i.stack.imgur.com/vVYLX.png
Image in runtime: http://i.stack.imgur.com/A0mLQ.png

Even if my settings is set to the original, it does not go centre/in the middle. If i remove the ActiveLabel from my UILabel, it works perfect.

**Comment by poolqf** [comment]
Related to #24

**Comment by xScylez** [comment]
@poolqf Did you manage to fix this somehow?

**Comment by poolqf** [comment]
@xScylez Fixed on the last release
