### ISSUE TITLE
Incorrect work with "-" symbol

### ISSUE THREAD

**Issue by keynsianets** [optonaut/ActiveLabel.swift#300]
If mention contain "-" symbol, like "@a-bus", this framework doesn't recognize it as mention. Or, if mention looks like a "@bro-card", it recognizes only first part of mention, before "-" symbol. Need to change regex expression.

**Comment by jkpang** [comment]
You can try `(?:^|\\s|$|[.])@[\\p{L}0-9_-]*`
@keynsianets 
<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by keynsianets** [comment]
Can be solved with use custom type. Example:
`let customType = ActiveType.custom(pattern: "(?:^|[^a-zA-Z0-9_＠!@#$%&*])(?:(?:@|＠)(?!\\/))([a-zA-Z0-9/_.'-]{1,15})(?:\\b(?!@|＠)|$)")
        label.enabledTypes = [customType]
        label.customColor = [customType : .black]`

**Comment by jkpang** [comment]
Good job 👍

**Comment by jjnino** [comment]
The default mention regex also doesn't recognize "." in the middle of a name. @John.doe for, example. 

I know I could use a custom type but the custom type is already being used for team mentions in the app. (@@teamname)

Could this be supported in the normal mention type?  ( "." and "-" )

**Comment by maziyarpanahi** [comment]
I think it’s best to work on making customType to not to be limited in one type. This way we can create customType as many as needed. It’s pitty to have only one customType option.
