### ISSUE TITLE
Mention Contact is not detect-> Image Included

### ISSUE THREAD

**Issue by olivinesguerra** [optonaut/ActiveLabel.swift#307]
Hi.

Please see the screenshots below. The hastag/s are all working but the mentioned contact is not
![screen shot 2019-03-05 at 11 05 38 pm](https://user-images.githubusercontent.com/5746116/53814815-5b8da100-3f9b-11e9-82cc-65bb3742b581.png)
![screen shot 2019-03-05 at 11 05 32 pm](https://user-images.githubusercontent.com/5746116/53814820-5deffb00-3f9b-11e9-81d8-1c19edfa7362.png)

BTW this is loaded from a tableview cell.

Thanks for any help 💃

**Comment by maziyarpanahi** [comment]
Hashtags are being used as a real hashtags in Twitter or anywhere else. But the mention with double @ is not a mention. You need to use custom pattern if this is the way you mention someone! 
Or if this is a fault of user, either let it be like if I don’t use mention correctly Twotter won’t change its rules for me or remove every @ followd by another @ before you display it on your app.
Either, that is not how use mention. This is @olivinesguerra
