### ISSUE TITLE
Custom type not working inside scroll view

### ISSUE THREAD

**Issue by antekarin** [optonaut/ActiveLabel.swift#310]
The tap doesn't respond inside a scroll view. I tried custom type only, can't say for others. Weird thing I found out is that if you scroll the scroll view and tap while its scrolling it works. I was thinking it was due delayed content touches but doesn't seems so.

**Comment by Jacolack** [comment]
I found a solution.
For me, I also had a `UIScrollView` and the Custom types weren't working in it unless I slightly scrolled while tapping. I remembered I have a `UITapGestureRecognizer` on my entire view, and I set
```swift
gestureRecognizer.cancelsTouchesInView = false
```
and the ActiveLabel works perfectly!
