### ISSUE TITLE
Invalid intrinsicContentSize with bold style of active elements

### ISSUE THREAD

**Issue by lancheg** [optonaut/ActiveLabel.swift#312]
I'm trying to set **bold** style for the active content, but **bold** text is longer than regular text, and label carries it to a new line.

For example, this is original text:
<img width="400" alt="Снимок экрана 2019-03-22 в 22 21 51" src="https://user-images.githubusercontent.com/15152482/54841398-0bc80d00-4cf1-11e9-8877-5bcde3af39ba.png">

This is what I want to reach:
<img width="400" alt="Снимок экрана 2019-03-22 в 22 13 03" src="https://user-images.githubusercontent.com/15152482/54841138-6f9e0600-4cf0-11e9-81e4-cd176453ccac.png">

But this is what I get:
<img width="400" alt="Снимок экрана 2019-03-22 в 22 13 03" src="https://user-images.githubusercontent.com/15152482/54841154-79c00480-4cf0-11e9-8363-add51c0c7ee3.jpg">

Thank you for your library!)

**Comment by maziyarpanahi** [comment]
Thanks for making a pull request, I will include it in the next release with Swift 5.0 👍
