### ISSUE TITLE
NSLocalizedString creates layout problem

### ISSUE THREAD

**Issue by albarq** [optonaut/ActiveLabel.swift#320]
Hi,
 I am using latest version of Active label library 

It was working fine with English language, but when started to localized words like following it start showing layout problem ..

in Localisation file
"test writing text for active label" = "تجربة كتابة عربية للاكتف لابيل";

in code:
label.customize{ label in
                    
                   
                        label.text = NSLocalizedString("test writing text for active label", comment: "")
                    
                    label.sizeToFit()
                    label.adjustsFontForContentSizeCategory = true
                    
                    label.font = UIFont.preferredFont(forTextStyle: .footnote)
                    
                    label.textColor = UIColor.contentText2
                    label.handleHashtagTap { hashtag in
                        print("Success. You just tapped the \(hashtag) hashtag")
                    }

}

but result showing one word missing لابيل
<img width="337" alt="Screen Shot 2019-05-03 at 8 13 47 PM" src="https://user-images.githubusercontent.com/3009026/57153856-05dd4580-6de0-11e9-9d58-73b7a9600752.png">

can you help please

**Comment by maziyarpanahi** [comment]
I am not sure if it helps, but you should always use fonts who support RTL languages. We've had some weird stuff happening with RTL languages and the solution was to use a font that supports RTL languages and not just a default font.

**Comment by albarq** [comment]
👍👍

Thanks a lot maziyarpanahi for your advice.


It works, when i used this font 

label.font = UIFont.init(name: "Arial", size: 20)

many thanks to you

**Comment by maziyarpanahi** [comment]
I am glad it helped 👍
