### ISSUE TITLE
App getting crash when set messageTextLbl.enabledTypes = [.url]

### ISSUE THREAD

**Issue by surani444** [optonaut/ActiveLabel.swift#323]
App getting crash when set messageTextLbl.enabledTypes = [.url], no any error message.
https://drive.google.com/file/d/14iJ-zYOkkr0CRz60tXoQolR2rdZOn4M6/view?usp=sharing

**Comment by salztorte** [comment]
I have the same problem. 
What was your solution?

**Comment by salztorte** [comment]
Ok this error was my fault. I used a TextView element and not a UILabel

**Comment by salztorte** [comment]
Was my fault.

In the storyboard i set the class to ActiveLabel but not the Module.

If i set both to ActiveLabel all worked.

**Comment by surani444** [comment]
Ya, it's work fine thank you @salztorte
