### ISSUE TITLE
google.com not detect

### ISSUE THREAD

**Issue by surani444** [optonaut/ActiveLabel.swift#324]

**Comment by maziyarpanahi** [comment]
Because it's not a URL. (http, https)

**Comment by surani444** [comment]
I solved this issue using NSDataDetector.

`static func getElements(from text: String, with pattern: String, range: NSRange) -> [NSTextCheckingResult]{
        let types: NSTextCheckingResult.CheckingType = .link
        
        let detector = try? NSDataDetector(types: types.rawValue)
        
        let matches = detector!.matches(in: text, options: .reportCompletion, range: NSMakeRange(0, text.count))
        
        return matches
    }`

replace this function
