### ISSUE TITLE
How to make two word with mention color?

### ISSUE THREAD

**Issue by iAmiOS** [optonaut/ActiveLabel.swift#329]
I have first name and last name as follows - "Harshad Wagh" but I am getting @Harshad with mention color. I want @Harshad Wagh as whole words with mention color.

Please help me

**Comment by Yonodactyl** [comment]
Hey @iAmiOS 
You can create a custom type that your app will search for and then handle a custom tap. It would look like this:
```swift
let username = "@Harshad Wagh"
let customType3 = ActiveType.custom(pattern: "\\s\(username)\\b")
label.enabledTypes.append(customType3)

label.handleCustomTap(for: customType3) { self.alert("Username is", message: $0) }
```
Resulting in the Alert:

```
Username is
@Harshad Wagh
```

**Comment by ksojitra747** [comment]
I am also getting same issue. Can anyone help me to figure out this issue?
