### ISSUE TITLE
How to get all ?

### ISSUE THREAD

**Issue by clbemre** [optonaut/ActiveLabel.swift#330]
Hi, its great lib.!

How to get all mention/hashtag ?

Ex: #swift #library @optonaut @emre

label.getAllHashtag() -> [swift,library]
label.getAllMention() -> [optonaut,emre]

Is it possible?

**Comment by maziyarpanahi** [comment]
I don't think there is such a function. However, you can just re-use the same regex to extract the hashtags and mentions manually.

**Comment by clbemre** [comment]
@maziyarpanahi  How? 

another question -> looking for a library like this. for Textfield for input, i cant find. Do you know library?

**Comment by maziyarpanahi** [comment]
I am sorry that is not what this library is for. It's not meant to be used as a one-stop regex on a string. You should consider using other libraries for this specific feature.

**Comment by clbemre** [comment]
@maziyarpanahi  which? :) please send me:) thanks
