### ISSUE TITLE
How to set different fonts for Hashtag?

### ISSUE THREAD

**Issue by StellarKuldeep** [optonaut/ActiveLabel.swift#332]
I want to set different Font for HashTag and Normal text?

If is it possible then please let me know how can I differentiate the fonts for HashTag and Normal text?

**Comment by Yonodactyl** [comment]
In the Demo project there is some info on customizing the font. You can create a custom type with the following: 
```swift
let customType3 = ActiveType.custom(pattern: "\\shashtag\\b")
```
Then you can append it to the created label:
```swift
label.enabledTypes.append(customType3)
```
Then inside of your `label.customize` you can declare this command and change what it looks like:
```swift
label.configureLinkAttribute = { (type, attributes, isSelected) in
                var atts = attributes
                switch type {
                case customType3:
                    atts[NSAttributedString.Key.font] = UIFont.boldSystemFont(ofSize: 14)
                default: ()
                }
                
                return atts
            }
```
And change the `NSAttributedString.Key.font` to whatever you want!

Just remember that this will change all of the attributed text so if you are trying to just make hashtags bigger but not @ and random links bigger then you must have a different approach!
