### ISSUE TITLE
Linkable works only in first paragraph.

### ISSUE THREAD

**Issue by fxwx23** [optonaut/ActiveLabel.swift#34]
How can l make the all hashtags, mentions, and links linkable in this label below.
<img width="368" alt="2015-12-23 18 50 12" src="https://cloud.githubusercontent.com/assets/7478439/11974308/47cfcb90-a9a6-11e5-8234-61c3ce6a28e9.png">
Including line breaks in texts, linkable doesn't work too.
What I miss something when the label's set upped ?
Thanks in beforehand.

**Comment by poolqf** [comment]
Not happening anymore
