### ISSUE TITLE
tap handle when other than url, mentioned or custom type tapped

### ISSUE THREAD

**Issue by ajkerfaisal** [optonaut/ActiveLabel.swift#342]
Let say I have this text

"Lorem pipsum https://www.google.com. pipusum lorementadiyo iblisiya. pipusum lorementadiyo iblisiya. pipusum lorementadiyo iblisiya"

I know when URL is tapped. Now I want to detect when other normal texts are tapped.

**Comment by awais-ijaz-brainx** [comment]
my issue is the same  I want to detect when other normal texts are tapped.
