### ISSUE TITLE
module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

### ISSUE THREAD

**Issue by devny** [optonaut/ActiveLabel.swift#343]
Hi. I am using ActiveLabel with Carthage.
After updating to Xcode 11.1 and building, ActiveLabel generates the following error message.

module compiled with Swift 5.0.1 cannot be imported by the Swift 5.1 compiler

Please answer me what to do.

**Comment by maziyarpanahi** [comment]
Your answer is very simple, the library is compatible with Swift `5.0`. Don't target `5.1`! I think the error is pretty clear.
