### ISSUE TITLE
How do I recognize text without a space separator

### ISSUE THREAD

**Issue by MuRanJiangXia** [optonaut/ActiveLabel.swift#349]
How do I recognize text without a space separator

like qweecyan  -> cyan .

What about special symbols？
```
like qwee <cyan>  -> <cyan> .   
```

**Comment by angeHi** [comment]
try:
let customType = ActiveType.custom(pattern: "cyan")

**Comment by MuRanJiangXia** [comment]
Thank you！
How do I add underline Style ？
