### ISSUE TITLE
not working Attributed string with range

### ISSUE THREAD

**Issue by tiskender2** [optonaut/ActiveLabel.swift#351]
`  let attributedText = NSMutableAttributedString(string: postContent)
      mentionRange = NSRange(location: 0, length: 10)
      attributedText.addAttribute(NSAttributedString.Key.underlineStyle , 
                                                      value:NSUnderlineStyle.single.rawValue, range: mentionRange!)
      attributedText.addAttribute(.backgroundColor , 
                                                      value: UIColor.red, range:  NSMakeRange(0, 10))
       activeLabel.attributedText = attributedText
`
  
### instead of range  it's set attributed whole text

**Comment by gerchicov-bp** [comment]
AND? It still doesn't work

**Comment by Sejmet** [comment]
AND?
