### ISSUE TITLE
Action label Not working in Japanese Text

### ISSUE THREAD

**Issue by thuanuit96** [optonaut/ActiveLabel.swift#357]
let customType = ActiveType.custom(pattern: "\\sを確認するか\\b") //Looks for "are"
        let customType2 = ActiveType.custom(pattern: "\\sit\\b") //Looks for "it"
        let customType3 = ActiveType.custom(pattern: "\\ssupports\\b") //Looks for "supports"

        label.enabledTypes.append(customType)
        label.enabledTypes.append(customType2)
        label.enabledTypes.append(customType3)
        label.customize { label in
            label.text = "で受信したコードを入力します。電子メールを受信していない場合には、迷惑メールフォルダーを確認するか、もう一度"
          }

**Comment by lizhaobomb** [comment]
maybe remove the \\s and \\b have a try
