### ISSUE TITLE
VoiceOver support

### ISSUE THREAD

**Issue by andreadelfante** [optonaut/ActiveLabel.swift#358]
Hi, it would be great to add support for VoiceOver.

Currently VoiceOver reads all the text in an ActiveLabel, but urls, mentions and hashtags are skipped from VoiceOver focus.

A solution would be to perform a whole text reading, then VoiceOver focuses on every actionable elements (urls, mentions and hashtags).

**Comment by andreadelfante** [comment]
Hi, any updates?

**Comment by maziyarpanahi** [comment]
This sounds like a nice feature, however, I don't have the skill to add/fix this. If there is any PR I can merge for the next release.
