### ISSUE TITLE
please update pods according to new release of ios 13.4

### ISSUE THREAD

**Issue by ravipromact2306** [optonaut/ActiveLabel.swift#359]
![Screenshot 2020-03-26 at 5 42 49 PM](https://user-images.githubusercontent.com/60922861/77646090-e0be6c00-6f89-11ea-924a-33bfd628ea94.png)

receiving this error in ios 13.4.

**Comment by TankarShah07** [comment]
@ravipromact2306 Yes I am also having the exact issue. Can anyone help how to resolve?

**Comment by jjnino** [comment]
same here.

**Comment by casperson** [comment]
Also seeing the issue, opened a PR here: https://github.com/optonaut/ActiveLabel.swift/pull/360

**Comment by maziyarpanahi** [comment]
I made a release 1.1.5 including the fix by @casperson for this issue. I asked to be published on cocoapods (I don't have permission for this)

https://github.com/optonaut/ActiveLabel.swift/releases/tag/1.1.5
