### ISSUE TITLE
AutoLayout Not Working Correctly with ActiveLabel

### ISSUE THREAD

**Issue by maddisonb** [optonaut/ActiveLabel.swift#36]
I'm using ActiveLabel as the Custom Class for my post’s content labels in the Storyboard; however, I believe it is interfering with Autolayout. For some reason the post’s content gets cut off (screenshot attached).

I guess it’s hard to know without seeing my code - but do you have a clue why this might be? 

![img_1008](https://cloud.githubusercontent.com/assets/6601425/12025778/ea520a68-ad66-11e5-953d-fdc27e5815d6.PNG)

**Comment by poolqf** [comment]
Sorry, I cannot understand your problem.
Do you mean that the text gets cut of on the right side of the cell?

**Comment by hdogan** [comment]
It breaks sentences as seen on screenshot. (As seen on first cell on screenshot "Palmer is throwing down tonight at 11pm. Theme").

I've tested with using "HelveticaNeue" font on custom table cell. But when I switch another font (tested with Avenir Next and San Francisco) it works as expected.

**Comment by OmerCora** [comment]
setting the line count of the label to "0" fixed this issue for me but i am having some auto-layout issues too, my dynamic cell height cant properly calculated.

**Comment by hdogan** [comment]
Labels' `numberOfLines` values are already set `0` when testing.

**Comment by MBLESSEN** [comment]
I'm having the same problem anyone figure this out?

**Comment by MBLESSEN** [comment]
Does anyone have a fix for custom fonts and auto layout? any ideas on how to fix this i the source code?

**Comment by Suleiman19** [comment]
What @hdogan suggested, worked for me.

**Comment by iantheparker** [comment]
+1

**Comment by saxahan** [comment]
Yes I've also had this issue. I had to make my label's font to System. Font style doesn't work either.

**Comment by poolqf** [comment]
Hi guys, merged #46 . Please check if this is issue is fixed with it and let me know :wink:
