### ISSUE TITLE
Add detection for .@username

### ISSUE THREAD

**Issue by poolqf** [optonaut/ActiveLabel.swift#37]
The `dot`+`user mention`(.@poolqf) is a common pattern in twitter for example.
Maybe we could add this exception in the regex.

@schickling could you help me on that? I'm not very good with regex

Thanks

**Comment by schickling** [comment]
So the dot should be ignored, right?

**Comment by poolqf** [comment]
Yep, enabling the mention to be tapped :smile:

**Comment by poolqf** [comment]
#40 fixed it
