### ISSUE TITLE
It seems that handle taps do not work 0.3.7

### ISSUE THREAD

**Issue by dimanicholson** [optonaut/ActiveLabel.swift#38]
Thank you guys! It's the best what I've seen!
So I'm not sure but it seems like handles do not work in 0.3.7. I downloaded and compiled source code folder 0.3.7 and 0.3.6. In 0.3.6 handleMentionTap, handleHashtagTap, handleURLTap working as expected. In 0.3.7 they don't work.

**Comment by poolqf** [comment]
What do you mean by "they don't work as expected"? Could you tell us where are you adding the label and what do you set to it?

**Comment by dimanicholson** [comment]
![screen shot 2016-01-03 at 06 24 12](https://cloud.githubusercontent.com/assets/15811407/12077153/1a0fdc22-b1e4-11e5-8cd5-0534623bdb44.png)
methods:
![screen shot 2016-01-03 at 06 28 33](https://cloud.githubusercontent.com/assets/15811407/12077155/22622b78-b1e4-11e5-9e57-df74c4d925cc.png)

**Comment by dimanicholson** [comment]
I mean UIAlertController doesn't appear

**Comment by dimanicholson** [comment]
Maybe I'm doing something wrong, maybe these methods really don't work. Check it just in case please.

**Comment by poolqf** [comment]
Yesterday I was working with ActiveLabel in the example project, and everything was working fine for me, alerts where being shown...

What Xcode version are you using?
Have you tried it in the example or in you own app?

**Comment by dimanicholson** [comment]
Xcode 7.2. It seems the problem is strange positioning of ActiveLabel and behaviour UITouch. I recorded the screencast: https://vimeo.com/150638370
Now I use 0.3.6 and it works fine. So If it's only my problem, I think we could close this issue. And I'll just continue to use 0.3.6.

**Comment by poolqf** [comment]
That's really strange, have you tried changing the zoom in the simulator to see the full screen?

I'll take a deeper look when I can, and I'll tell you something

**Comment by dimanicholson** [comment]
I think the problem is the arbitrary height of ActiveLabel: https://vimeo.com/150716211

**Comment by poolqf** [comment]
Wow, you are totally correct. I now see the point! 
The thing is that is not taking the inset in account. I'll take a look at it right now

**Comment by poolqf** [comment]
Could you check the referenced PR, I think it is now doing what is expected

**Comment by dimanicholson** [comment]
Yes, I checked it. Now all works great! With labels of any height! Thank you!
