### ISSUE TITLE
RTL support issue 

### ISSUE THREAD

**Issue by engsulta** [optonaut/ActiveLabel.swift#384]
I have tried to set RTL text  but am not sure why the text size calculation always not correct as I noticed that the text shown  is always less than the original text and no hashtag detected 
did anyone face this issue before? 
example 
label.text = "صباح الخير  لتقليل مسامات الوجه  استعمل غسول مجفف للبشرة  استعمل مرطب بشكل دائم مناسب لبشرتك  استعمل مقشرات البشرة الطبية مثل ادابالين ليلاً  يمكن استعمال الليزر الفراكشنال لتقليل المسامات #طبيب #أخبار_طبية #جلدية"

**Comment by engsulta** [comment]
"صباح الخير  لتقليل مسامات الوجه  استعمل غسول مجفف للبشرة  استعمل مرطب بشكل دائم مناسب لبشرتك  استعمل مقشرات البشرة الطبية مثل ادابالين ليلاً  يمكن استعمال الليزر الفراكشنال لتقليل المسامات #طبيب #أخبار_طبية #جلدية"

**Comment by freelancerios** [comment]
@engsulta if you are using System font then this issue appear.

for reference check issue #154

**Comment by X901** [comment]
This issue appear with system font or custom fonts, only  if the language is Arabic language !
