### ISSUE TITLE
URL detection issue

### ISSUE THREAD

**Issue by chetanPuwar21** [optonaut/ActiveLabel.swift#394]
"google.com", "google.uk" is not detected as a URL

**Comment by chetanPuwar21** [comment]
Solved:- 
static let urlPattern = "((?:http|https)://)?(?:www\\.)?[\\w\\d\\-_]+\\.\\w{2,3}(\\.\\w{2})?(/(?<=/)(?:[\\w\\d\\-./_]+)?)?"

**Comment by shgew** [comment]
+1
As a temporary solution, you can provide a custom regex which would suit your needs via `ActiveType.custom(pattern:)`.
