### ISSUE TITLE
How do I detect the tap of the rest of the text

### ISSUE THREAD

**Issue by buluoray** [optonaut/ActiveLabel.swift#398]
I would like to know how to detect text other than the one I set. For example, I set I only want Hashtag, and I will also get a callback when I tap text other than hashtag

**Comment by buluoray** [comment]
I figured it out.

**Comment by krgoodnews** [comment]
How did you solve it?
@buluoray

**Comment by ibarisic05** [comment]
@krgoodnews you can use custom type with regex pattern, had success with this: 

```
let customType = ActiveType.custom(pattern: "(?:^|(?<= ))([^#|^@]+)")
label.enabledTypes = [.hashtag, .mention, customType]
```

**Comment by buluoray** [comment]
@krgoodnews I modified the package. Basically, add an else statement in onTouch case .ended

`case .ended, .regionExited:
            guard let selectedElement = selectedElement else {
                didTapNormalText()
                return avoidSuperCall
            }`
            
  ` fileprivate func didTapNormalText() {
        guard let textTapHandler = textTapHandler else {
            delegate?.didSelect("Tap normal text", type: .custom(pattern: ""))
            return
        }
        textTapHandler()
    }`

`internal var textTapHandler: (() -> ())?`
