### ISSUE TITLE
Handle tap is triggered on scroll when touch down started on a url/mention/hashtag

### ISSUE THREAD

**Issue by alexbredy** [optonaut/ActiveLabel.swift#43]
When scrolling on a table view and a tap is done on a url (for example), the handleTap block is triggered (opening a web browser in my case) thus troubling the experience of the users when they only want to scroll. Could it be possible to trigger the block exclusively on touch up? (or if not, add an option to it?)
Great plug-in by the way!

**Comment by poolqf** [comment]
Yep. I am aware of that, the canceled touch is not handled correctly. Will take a look when possible
