### ISSUE TITLE
Links without http and https are not clickable

### ISSUE THREAD

**Issue by rajesh-situ** [optonaut/ActiveLabel.swift#48]
Update the below method
private func didTapStringURL(var stringURL: String) {
        if !(stringURL.containsIgnoreCase("http")) {
            stringURL = "http://" + stringURL
        }
        guard let urlHandler = urlTapHandler, let url = NSURL(string: stringURL) else {
            delegate?.didSelectText(stringURL, type: .URL)
            return
        }
        urlHandler(url)
    }

**Comment by dsinkovskiy** [comment]
Hi @rajesh-situ, check out my pull request #78. Your problem is solved.

**Comment by nshiva1998** [comment]
You can add custom type 👍 , this is working for me

        lable.enabledTypes = [.url]
        let regex = "((http|https|ftp)://)?((\\w)*|([0-9]*)|([-|_])*)+([\\.|/]((\\w)*|([0-9]*)|([-|_])*))+"
        let customType = ActiveType.custom(pattern: regex)
        lable.customColor[customType] = UIColor.blue
        lable.enabledTypes.append(customType)
        lable.configureLinkAttribute = { (type, attributes, isSelected) in
            var atts = attributes
            atts[NSAttributedString.Key.underlineStyle] = NSUnderlineStyle.single.rawValue
            return atts
        }
