### ISSUE TITLE
URLEnabled & hashtagEnabled properties not available in CocoaPod 0.4.1

### ISSUE THREAD

**Issue by emjoseph** [optonaut/ActiveLabel.swift#52]
Hey just ran my app with the latest Cocoapod (0.4.1) and it crashed cause the URLEnabled and hashtagEnabled properties are missing.

Here's an image of the log:
(https://cloud.githubusercontent.com/assets/4806770/13538667/c7e140e2-e200-11e5-8ec8-9537483de568.png)

**Comment by poolqf** [comment]
These properties are no longer existing. See https://github.com/optonaut/ActiveLabel.swift/pull/51
