### ISSUE TITLE
empty space interaction on the last line

### ISSUE THREAD

**Issue by thelittlesaul** [optonaut/ActiveLabel.swift#57]
![simulator screen shot 21 mar 2016 5 55 08 pm](https://cloud.githubusercontent.com/assets/16758197/13915261/9d792a18-ef8e-11e5-98dc-e5efa38a6ee8.png)

I supposed it should not invoke the tapHandler when tapping space with no text on the last line, as shown in  attached screenshot. Does it makes sense to you?

**Comment by poolqf** [comment]
It is one of our trickiest issues.. Would love to fix it, but haven't found a good solution tbh
