### ISSUE TITLE
Partially working on Custom UITableViewCell

### ISSUE THREAD

**Issue by fatihyildizhan** [optonaut/ActiveLabel.swift#63]
Handle functions are not working until scrolling the tableview. While scrolling handle functions are working for a moment. It's hard to describe but, cell is on Storyboard. It has single UILabel and constraints, using system-regular font and it's multiline. 

Do you know anything about this issue?

By the way, it is working on clean UITableView. Unfortunately it is not possible to start making the tableview from the beginning.

Than you in advance.

**Comment by poolqf** [comment]
> Handle functions are not working until scrolling the tableview

Could you be more specific? I am using ActiveLabel in a lot of table views inside my app without any kind of problems

**Comment by telip007** [comment]
Links inside of custom UITableViewCell aren't clickable or react after I press 10 times or more...

**Comment by telip007** [comment]
@fatihyildizhan could you solve it ?

**Comment by fatihyildizhan** [comment]
Not yet.

**Comment by telip007** [comment]
Hm..

**Comment by Econa77** [comment]
@fatihyildizhan Do you use the UITapGesture in View of UITableView or parent?

**Comment by sluitel** [comment]
Having the same issue. mentions, hashtags inside custom uitableviewcell are not clickable. I do not use UITapGesture in View of UITableView or parent. Custom tableViewCell is implanted via auto layout. I can click on the mentions once is about 10 tries. Below is my code

```
cell.commentLabel.handleMentionTap({ (userId) in
     print("mention clicked" )           
 })
```

here, commentLabel is the activeLabel

**Comment by fatihyildizhan** [comment]
@Econa77 No, I am not using UITapGesture

**Comment by poolqf** [comment]
Hi @sluitel , @fatihyildizhan , could you create a project to replicate it? I cannot make it happen 😕

**Comment by s4cha** [comment]
Same issue here ;)

**Comment by poolqf** [comment]
Guys, if you don't give me more context or create a dummy project to replicate it I cannot help!

cc/ @s4cha @sluitel @fatihyildizhan

**Comment by sluitel** [comment]
Actually, I found out that I had a tap gesture recognizer on the table view. It started working once I removed that. Thank you.

**Comment by em254** [comment]
it crashed on me:
Code is like below in my UITableView cellForRowAt function.

`            cell.CommentLbl.numberOfLines = 0
            cell.CommentLbl.text = CommentsCard.CommentText
            cell.CommentLbl.enabledTypes = [.url, .hashtag]
            cell.CommentLbl.textColor = .blue
            cell.CommentLbl.handleURLTap({ (url) in
                print("mention clicked \(url)" )
            })
`
CommentLbl is ActiveLabel and CommentsCard is Realm object.. Any help>

**Comment by pushkardeshmukh1992** [comment]
@sluitel thanks, it worked!
