### ISSUE TITLE
Support Phone Number detect

### ISSUE THREAD

**Issue by seapy** [optonaut/ActiveLabel.swift#66]
Hi, 
ActiveLabel.swift is very useful and thank you.

I have a suggestion. Phone Number is important element is phone system. it looks like URL.
How about support detect Phone Number?

**Comment by poolqf** [comment]
Hi @seapy, as I said you in the PR, we should find a good regex that accepts all the countries phone number.

**Comment by dsinkovskiy** [comment]
Hi @seapy, check out my pull request #78

**Comment by NikKovV** [comment]
What about phone detection. Add this and this pod will be irreplaceable!=)

**Comment by poolqf** [comment]
Phone numbers detection is a really tricky game. Since @seapy did not maintain the PR he opened, and it is not on our roadmap, I'll close the issue
