### ISSUE TITLE
Support Truncation Token

### ISSUE THREAD

**Issue by Ferrick90** [optonaut/ActiveLabel.swift#80]
able to set numberOfLines = 4 once the text over 4 lines it will show ...More? And, ...More able to let user to press it.

**Comment by poolqf** [comment]
Could you explain the issue a little bit more @Ferrick90 ?

**Comment by Ferrick90** [comment]
Hi @poolqf ,

<img width="354" alt="screen shot 2016-05-06 at 6 50 54 pm" src="https://cloud.githubusercontent.com/assets/6068413/15071081/916aadc2-13bb-11e6-919b-bc5daaf454d5.png">

It almost like [ResponsiveLabel](https://github.com/hsusmita/ResponsiveLabel) can be expand to show all the text. could ActiveLabel do that?

**Comment by poolqf** [comment]
Nope @Ferrick90 , ActiveLabel cannot do that, and it is not planned to implement it. But PR are always welcome 😄
