### ISSUE TITLE
Expose rect of tapped element

### ISSUE THREAD

**Issue by cannyboy** [optonaut/ActiveLabel.swift#84]
I'd like to know the tap location (or rect of tapped hashtag) so that I can present a popover (on iPad) at the correct location.

![screen shot 2016-06-01 at 17 24 42](https://cloud.githubusercontent.com/assets/1590436/15717232/f9edfa90-281d-11e6-9d2c-b4b26c48015a.png)

````
activeLabel.text = "This is a @test with various @mentions and #hashtags and http://urls.com"
activeLabel.handleHashtagTap { (hashtag) in       
    let alert = UIAlertController(title: "open #" + hashtag, message: "", preferredStyle: .ActionSheet)
    alert.addAction(UIAlertAction(title: "Twitter", style: .Default, handler: nil))
    alert.addAction(UIAlertAction(title: "Instagram", style: .Default, handler: nil))
            
    let popover = alert.popoverPresentationController
    if let popover = popover {
        popover.sourceView = self.activeLabel
        popover.sourceRect = self.activeLabel.bounds
        popover.permittedArrowDirections = .Any
    }
    self.presentViewController(alert, animated: true, completion: nil)
}
````

You can see in the above that I'm using the ActiveLabel as the source view, so the popover's arrow comes from the edge of it, but it would be neat to know where the actual word is, so the arrow can point to it.

**Comment by poolqf** [comment]
It is not on our roadmap, sorry... feel free to open a PR
