### ISSUE TITLE
When i set class to ActiveLabel to storyboard xCode 8 Failed

### ISSUE THREAD

**Issue by paneaktae** [optonaut/ActiveLabel.swift#86]
How to fix, When i set ActiveLabel to UILabel class in storyboard , xCode 8 Storyboard failed to render auto layout

**Comment by poolqf** [comment]
Try `swift3` branch. It is still a WIP, so I am not 100% sure it will work

**Comment by dimovskidamjan** [comment]
@poolqf The swift3 branch has not been approved yet. How could I use it?

**Comment by poolqf** [comment]
You should point to the branch. In the following days I am gonna merge and prepare a release 😄
