### ISSUE TITLE
Bad test design

### ISSUE THREAD

**Issue by guillermomuntaner** [optonaut/ActiveLabel.swift#87]
Just a pedant issue!

While playing and trying to improve the regexs i found a bad test design. Your test code is written to succeed, but does not handle failure well. Problem is caused because you don't prevent "inner" assertion execution when "outer" asserts fails and this leads to a `currentElementString/currentElementType .first!` un-wrapp crash.

E.g, this test of comma-mention test cause an exception instead of an assertion failure.
```
label.text = ",@userhandle"
XCTAssertEqual(activeElements.count, 1) // This evaluates to false, which is OK
XCTAssertEqual(currentElementString, "userhandle") // But then currentElementString will fail becouse activeElements.first!
XCTAssertEqual(currentElementType, ActiveType.Mention)
```

This would be the good way; test fails without crashing:
```
label.text = ",@userhandle"
XCTAssertEqual(activeElements.count, 1)
if(activeElements.count>0) {
    XCTAssertEqual(currentElementString, "userhandle")
    XCTAssertEqual(currentElementType, ActiveType.Mention)
}      
```

**Comment by poolqf** [comment]
Agree with you about the force unwrap, but not about the implementation you suggest. I rather prefer to return an optional in `currentElementString` and `currentElementType`, than having an if.

A test should only have one path of execution. Otherwise you need 2 tests.

**Comment by poolqf** [comment]
Thanks for the heads up @guillermomuntaner, fixed in https://github.com/optonaut/ActiveLabel.swift/commit/fa897a0d1a9db9faf62a694caf844892527cf43d
