### ISSUE TITLE
Optimization: Do simple checks before using regex.

### ISSUE THREAD

**Issue by guillermomuntaner** [optonaut/ActiveLabel.swift#88]
I've seen this idea in a Twitter java implementation.

- **Urls**: Check if text contains **'.' or ':'**. If text doesn't contain '.' or ':' at all, text doesn't contain URL so skip url regex.
- **Mentions**: Check if text contains **'@'** . If text doesn't contain '@' at all, text doesn't contain mentions so skip mention regex.
- **Hashtags**: Check if text contains **'#'** . If text doesn't contain '#' at all, text doesn't contain hashtags so skip hashtag regex.

Note this checking might be optional. If developer knows for sure the texts will contain one of the elements, then this is actually slowing execution (but i think its a very very rare scenario). Also, i don't know the real impact of this in Swift since i havn't tested yet, but I guess this should improve since character search should be way faster than regex eval.

Source of the idea & good resource for regexs and matching:
https://github.com/twitter/twitter-text/blob/810c05271c6d295211760139f4ab04749495b38a/java/src/com/twitter/Extractor.java

**Comment by poolqf** [comment]
Really nice tips @guillermomuntaner , would be interesting to try it and do a benchmark to know if it could really help.

**Comment by guillermomuntaner** [comment]
Have been testing. 
Benefits are not as good as I expected, but might be noticeable. As expected, biggest benefit happens the longer the text is and only when it does not contain one/several of the elements ".",":","#","@".  Best case when text does not contain anything, but is quite unrealistic.
On the other hand, there is almost no penalization (worst case is -2.8% and -6% on long text)
 
For the checking I've been using. I don't know if there are faster ways to do it.
```
text.containsString("@")
text.containsString("@")
text.containsString(".") || text.containsString(":")
```

Format of results is:
> **Description**
> Exact text used
>  - Time for 1000 iterations without optimization
>  - Time for 1000 iterations with optimization
>  - % Diff. Positive means is faster (e.j. 3% faster) and negative means slower.


**Text with a simple mention:**
@userhandle:
 - NoOpt:        0.584077000617981s
 - Opt:          0.579048991203308s
 - Diff(% win):  0.868321936667954 %

**Text with a simple hashtag:**
#somehashtag:
 - NoOpt:        0.5832279920578s
 - Opt:          0.599614024162292s
 - Diff(% win):  -2.73276331843384 %

**Text with a simple url:**
http://www.google.com.:
 - NoOpt:        0.813069045543671s
 - Opt:          0.667460978031158s
 - Diff(% win):  21.8152180134963 %

**Medium-sized text without punctuation:**
Swift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a:
 - NoOpt:        0.947183012962341s
 - Opt:          0.624957978725433s
 - Diff(% win):  51.5594720294743 %

**Medium-sized text with punctuation**
Swift is a new programming language for iOS, OS X, watchOS, and tvOS apps that builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier:
 - NoOpt:        0.770547986030579s
 - Opt:          0.71908301115036s
 - Diff(% win):  7.15702833778354 %

**Medium-sized text with punctuation and hashtag**
Swift is a new progr#amming language for iOS, OS X, watchOS, and tvOS apps that builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier:
 - NoOpt:        0.751354992389679s
 - Opt:          0.750382959842682s
 - Diff(% win):  0.129538195696881 %

**Medium-sized text with punctuation and mention**
Swift is a new progr @amming language for iOS, OS X, watchOS, and tvOS apps that builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier:
 - NoOpt:        0.885190010070801s
 - Opt:          0.879595041275024s
 - Diff(% win):  0.636084622267319 %

**Medium-sized text with punctuation, mention and hashtag**
Swift is a new progra @mming language for iOS, OS X, watchOS, and tvOS apps that #builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier:
 - NoOpt:        0.975953996181488s
 - Opt:          1.00462198257446s
 - Diff(% win):  -2.8536093068071 %

**Long-sized text without punctuation**
Swift is a new programming language for Swift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for iSwift is a new programming language for i:
 - NoOpt:        1.86365300416946s
 - Opt:          1.33180302381516s
 - Diff(% win):  39.934582730616 %

**Long-sized text with punctuation**
Swift is a new programming language for iOS, OS X, watchOS, and tvOS apps that builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier, more flexible, and more fun. Swift’s clean slate, backed by the mature and much-loved Cocoa and Cocoa Touch frameworks, is an opportunity to reimagine how software development works. Swift has been years in the making. Apple laid the foundation for Swift by advancing our existing compiler, debugger, and framework infrastructure. We simplified memory management with Automatic Reference Counting (ARC). Our framework stack, built on the solid base of Foundation and Cocoa, has been modernized and standardized throughout. Objective-C itself has evolved to support blocks, collection literals, and modules, enabling framework adoption of modern language technologies without disruption. Thanks to this groundwork, we can now introduce a new language for the future of Apple software development. Swift feels familiar to Objective-C developers. It adopts the readability of Objective-C’s named parameters and the power of Objective-C’s dynamic object model. It provides seamless access to existing Cocoa frameworks and mix-and-match interoperability with Objective-C code. Building from this common ground, Swift introduces many new features and unifies the procedural and object-oriented portions of the language. Swift is friendly to new programmers. It is the first industrial-quality systems programming language that is as expressive and enjoyable as a scripting language. It supports playgrounds, an innovative feature that allows programmers to experiment with Swift code and see the results immediately, without the overhead of building and running an app.:
 - NoOpt:        2.01122599840164s
 - Opt:          1.75252997875214s
 - Diff(% win):  14.7612892667152 %

**Long-sized text with punctuation and hashtag**
Swift is a new programming language for iOS, OS X, watchOS, and tvOS apps that builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier, more flexible, and more fun. Swift’s clean slate, backed by the mature and much-loved Cocoa and Cocoa Touch frameworks, is an opportunity to reimagine how software development works. Swift has been years in the making. Apple laid the foundation for Swift by advancing our existi #hurray ng compiler, debugger, and framework infrastructure. We simplified memory management with Automatic Reference Counting (ARC). Our framework stack, built on the solid base of Foundation and Cocoa, has been modernized and standardi zed throughout. Objective-C itself has evolved to support blocks, collection literals, and modules, enabling framework adoption of modern language technologies without disruption. Thanks to this groundwork, we can now introduce a new language for the future of Apple software development. Swift feels familiar to Objective-C developers. It adopts the readability of Objective-C’s named parameters and the power of Objective-C’s dynamic object model. It provides seamless access to existing Cocoa frameworks and mix-and-match interoperability with Objective-C code. Building from this common ground, Swift introduces many new features and unifies the procedural and object-oriented portions of the language. Swift is friendly to new programmers. It is the first industrial-quality systems programming language that is as expressive and enjoyable as a scripting language. It supports playgrounds, an innovative feature that allows programmers to experiment with Swift code and see the results immediately, without the overhead of building and running an app.:
 - NoOpt:        2.10823601484299s
 - Opt:          2.00675201416016s
 - Diff(% win):  5.05712713712177 %

**Long-sized text with punctuation and mention**
Swift is a new programming language for iOS, OS X, watchOS, and tvOS apps that builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier, more flexible, and more fun. Swift’s clean slate, backed by the mature and much-loved Cocoa and Cocoa Touch frameworks, is an opportunity to reimagine how software development works. Swift has been years in the making. Apple laid the foundation for Swift by advancin @zed g our existing compiler, debugger, and framework infrastructure. We simplified memory management with Automatic Reference Counting (ARC). Our framework stack, built on the solid base of Foundation and Cocoa, has been modernized and standardized throughout. Objective-C itself has evolved to support blocks, collection literals, and modules, enabling framework adoption of modern language technologies without disruption. Thanks to this groundwork, we can now introduce a new language for the future of Apple software development. Swift feels familiar to Objective-C developers. It adopts the readability of Objective-C’s named parameters and the power of Objective-C’s dynamic object model. It provides seamless access to existing Cocoa frameworks and mix-and-match interoperability with Objective-C code. Building from this common ground, Swift introduces many new features and unifies the procedural and object-oriented portions of the language. Swift is friendly to new programmers. It is the first industrial-quality systems programming language that is as expressive and enjoyable as a scripting language. It supports playgrounds, an innovative feature that allows programmers to experiment with Swift code and see the results immediately, without the overhead of building and running an app.:
 - NoOpt:        2.06904697418213s
 - Opt:          2.02681803703308s
 - Diff(% win):  2.0835090460742 %

**Long-sized text with punctuation, mention and hashtag**
Swift is a new programming language for iOS, OS X, watchOS, and tvOS apps that builds on the best of C and Objective-C, without the constraints of C compatibility. Swift adopts safe programming patterns and adds modern features to make programming easier, more flexible, and more fun. Swift’s clean slate, backed by the mature and much-loved Cocoa and Cocoa Touch frameworks, is an opportunity to reimagine how software development works. Swift has been years in the making. Apple laid the foundation for Swift by advancing our existi #hurray ng compiler, debugger, and framework infrastructure. We simplified memory management with Automatic Reference Counting (ARC). Our framework stack, built on the solid base of Foundation and Cocoa, has been modernized and standardi @zed throughout. Objective-C itself has evolved to support blocks, collection literals, and modules, enabling framework adoption of modern language technologies without disruption. Thanks to this groundwork, we can now introduce a new language for the future of Apple software development. Swift feels familiar to Objective-C developers. It adopts the readability of Objective-C’s named parameters and the power of Objective-C’s dynamic object model. It provides seamless access to existing Cocoa frameworks and mix-and-match interoperability with Objective-C code. Building from this common ground, Swift introduces many new features and unifies the procedural and object-oriented portions of the language. Swift is friendly to new programmers. It is the first industrial-quality systems programming language that is as expressive and enjoyable as a scripting language. It supports playgrounds, an innovative feature that allows programmers to experiment with Swift code and see the results immediately, without the overhead of building and running an app.:
 - NoOpt:        2.14058703184128s
 - Opt:          2.27751898765564s
 - Diff(% win):  -6.0123299325514 %

**Comment by poolqf** [comment]
Hi @guillermomuntaner, thank you a lot for this benchmark!!! 😍 

I am a bit worried about the `Long-sized text with punctuation, mention and hashtag` one.
Even that it is just a `-6`% of penalisation, having all the possible elements (username, hashtag and punctuation) is one of the most common use cases of the developers using ActiveLabel...

Would also be good to know if there's a more efficient way to check than `containsString`🤔

Another time, thanks for the investigation you've done, it's awesome!
