### ISSUE TITLE
Usernames with periods are not fully highlighted

### ISSUE THREAD

**Issue by ajfigueroa** [optonaut/ActiveLabel.swift#9]
Would it be possible to expand the search for usernames to include ones that have periods in them, such as my name "@alex.figueroa"? It is currently being highlighted only until the period. (It seems Github does this with their markdown too 😅)

![activelabelscreenshot](https://cloud.githubusercontent.com/assets/3321592/10080746/67bb8a12-62bf-11e5-848b-1b97ee6485e5.png)

**Comment by schickling** [comment]
Yeah, I agree that might be a problem. At the moment usernames aren't configured to include a dot. I'll consider for the next version. I'll be possible to override the default regex for a username/hashtag/link.

Would that work for you?

**Comment by ajfigueroa** [comment]
Yup, that is something that would work. Looking forward to the next iteration!

**Comment by poolqf** [comment]
Not happening anymore

**Comment by ajfigueroa** [comment]
No problem. Out of curiosity, what is the reasoning?

**Comment by poolqf** [comment]
@ajfigueroa This issue is no longer happening, usernames with periods are now highlighted, so that's why I am closing it

**Comment by ajfigueroa** [comment]
@poolqf Beautiful, thanks :)

**Comment by 2mittens** [comment]
Hello! It seems this is happening again. 
<img width="459" alt="screen shot 2016-05-31 at 10 46 50" src="https://cloud.githubusercontent.com/assets/4586785/15668740/0e05901c-271d-11e6-8af7-82432176e02e.png">
Any idea how to fix it?

Thank you!

**Comment by poolqf** [comment]
Reopening

**Comment by 2mittens** [comment]
After digging a bit in the sources, I noted that the Cocoapods regex is different from the GitHub one, maybe is outdated?

The problem however is present in both version, but I was able to solve it just adding **.** to the Cocopods one, having the whole regex like this:
`(?:^|\\s|$|[.])@[a-z0-9_.]*`

Does this help?

**Comment by poolqf** [comment]
Hm, strange the thing about the different regex, I'll take a look into it.

Yep, the regex needs to allow the `.` as a valid username character

**Comment by 2mittens** [comment]
Before any edits they're like this:

**GitHub:**
`(?:^|\\s|$|[.])@[\\p{L}0-9_]*`

**Cocoapods**
`(?:^|\\s|$|[.])@[a-z0-9_]*`

Adding a `.` to Cocoapds regex resolve the issue, but it doesn't on the repo one.

Hope I was helpful and thank you!

**Comment by poolqf** [comment]
`(?:^|\\s|$|[.])@[\\p{L}0-9_.]*` This regex is working for me

**Comment by 2mittens** [comment]
Also with mentions with a dot in it? Because for me is working for @userhandle, but not for @userhandle.dotted!

**Comment by poolqf** [comment]
https://regex101.com/r/kJ1pY6/1

**Comment by 2mittens** [comment]
My bad, I wasn't building properly the framework before testing the demo. So yes, just adding the point to the regex solves the matter.

Thanks for the help!

**Comment by MarvinNazari** [comment]
this issue is still happening, any workaround?

**Comment by poolqf** [comment]
There was a fix I reverted because of side effects...

**Comment by blixt** [comment]
We have this issue too. Is there a way to customize the Regex without cloning the project?

**Comment by demonar** [comment]
@polqf we have the same issue, should we fix it on our fork?, or wait for your solution?, i'm asking because you reverted a fix due to side effects.

**Comment by davidpflugpeil** [comment]
Are there any news on this?

**Comment by demonar** [comment]
same as #228, added some options of regex to fix it, will try to have a PR soon

**Comment by demonar** [comment]
i have a fix working, will make the changes in the swift 4 version and create the PR next week

**Comment by sampurnamishra-kiwi** [comment]
Hi, Text does not bold when word contain any special letter like (&, +, -). Please help me.
