### ISSUE TITLE
Unable to get .handleURLTap() to work

### ISSUE THREAD

**Issue by dotmat** [optonaut/ActiveLabel.swift#91]
1st off, this is awesome. Thank you for the work and effort!

I have ActiveLabel in a UITableViewCell: 

let label = ActiveLabel()
    var urlToLoad: String = ""

    lazy var bodyLabel: UILabel = {
        let label = ActiveLabel()
        label.URLColor = UIColor(red: 85.0/255, green: 238.0/255, blue: 151.0/255, alpha: 1)
        label.URLSelectedColor = UIColor(red: 82.0/255, green: 190.0/255, blue: 41.0/255, alpha: 1)
        label.font = UIFont.preferredFontForTextStyle(UIFontTextStyleBody)
        label.numberOfLines = 0
        label.lineSpacing = 4
        return label
    }()

It works fine and picks up the URL's 
If I put the .handleURLTap { self.alert("URL", message: $0.absoluteString) } code in the UITableViewCell then the code works and is executed but I can't segue from with UITableViewCell. 

If I put the code into:

    func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let cell = ...  // code removed 
    cell.label.handleURLTap({ NSURL in print("Success. Loading  \(NSURL)")})
    ..
    }

How do I call the URL thats inside the UITableViewCell from the UIViewController so I can load that URL?

**Comment by poolqf** [comment]
You should be able to make it work it you set a `handleURLTap` block
