### ISSUE TITLE
Handle tap if not on ActiveElement

### ISSUE THREAD

**Issue by johnstonmatt** [optonaut/ActiveLabel.swift#93]
Is there a way to handle all other taps on the label that don't match a specific active element, without breaking the active element detection?

**Comment by johnstonmatt** [comment]
I tried putting a UITapGestureRecognizer on the label but that breaks detection of taps on active elements.

**Comment by soapsign** [comment]
My suggestion would be use UITapGestureRecogniser to replace the ActiveLabel onTouch and exposing the recogniser. So you can use the UIGestureRecogniserDelegate to handle this.

**Comment by poolqf** [comment]
There is a work going on where you can provide a custom handler for an Element, so when it is done, you can create it, and give it the same text as the color, and you're going to have it.

But as I said, is a going on work ATM

**Comment by alkincakiralar1996** [comment]
i cant do it please help me i've been trying a lot of hours please
